/**
 * `fixtures/cc-2.1.283/` — the 0.9.2 corpus. Goldens, the tree it must build,
 * and the record type and keys Claude Code added since the last harvest,
 * pinned as observed.
 *
 * Two real sessions of one 4x2 nested run (four agents, each spawning two):
 * 12 subagents per session, 24 sidecars in all. This is the run whose
 * subagent pairs arrived half written — transcript first in 17 of 24 pairs,
 * the sidecar up to 372 ms later — and refused the whole session before the
 * ruling of 2026-09-29. The race itself is replayed in
 * `src/model/sidecar-race.test.ts` and `src/extension.test.ts`; this file
 * pins what the finished corpus reads as.
 *
 * Goldens live in `fixtures/golden/graft-cc-2.1.283/` and are regenerated by
 * running this file with `AGENT_DECK_UPDATE_GOLDENS=1` — the same rule as
 * `fixtures/golden/graft/`: read the diff before trusting it.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it, vi } from 'vitest';

// Every test here grafts a real 600 KB session, about a second each on an idle
// machine. vitest's 5 s default is a test that passes or fails by CPU load.
vi.setConfig({ testTimeout: 30_000 });
import type { AgentNode, TreeNode } from './events.js';
import { isAgentNode } from './events.js';
import { goldenText, graftSession } from './graft.js';
import { fingerprintSession } from '../parser/fingerprint.js';
import { IGNORED_ENTRY_TYPES, KNOWN_ENTRY_TYPES, parseLines } from '../parser/parse.js';

const FIXTURES = fileURLToPath(new URL('../../fixtures', import.meta.url));
const SLUG_DIR = join(FIXTURES, 'cc-2.1.283', 'projects', 'c--Users-dev-projects-agent-deck');
const GOLDEN_DIR = join(FIXTURES, 'golden', 'graft-cc-2.1.283');
const UPDATE_GOLDENS = process.env['AGENT_DECK_UPDATE_GOLDENS'] === '1';

async function sessionIds(): Promise<string[]> {
  return (await readdir(SLUG_DIR))
    .map((name) => /^(.+)\.jsonl$/.exec(name)?.[1])
    .filter((id): id is string => id !== undefined)
    .sort();
}

/** Every `.jsonl` file of the corpus, main transcripts and subagents alike. */
async function transcripts(): Promise<{ path: string; main: boolean }[]> {
  const out: { path: string; main: boolean }[] = [];
  for (const id of await sessionIds()) {
    out.push({ path: join(SLUG_DIR, `${id}.jsonl`), main: true });
    const dir = join(SLUG_DIR, id, 'subagents');
    for (const name of (await readdir(dir)).sort()) {
      if (name.endsWith('.jsonl')) out.push({ path: join(dir, name), main: false });
    }
  }
  return out;
}

async function linesOf(path: string): Promise<string[]> {
  return (await readFile(path, 'utf8')).split('\n').filter((line) => line.trim() !== '');
}

/** Every agent node under `node`, root included. Tools carry agents as children. */
function agentsIn(node: TreeNode): AgentNode[] {
  const out: AgentNode[] = [];
  const visit = (n: TreeNode): void => {
    if (isAgentNode(n)) out.push(n);
    for (const child of (n as { children?: readonly TreeNode[] }).children ?? []) visit(child);
  };
  visit(node);
  return out;
}

describe('cc-2.1.283 grafts whole', () => {
  it('holds the two sessions of the 4x2 run', async () => {
    expect(await sessionIds()).toEqual([
      '853296cc-eb78-4a6c-b747-cd5417473cc5',
      'd860ab28-db10-40dc-8775-ae00eeb21f23',
    ]);
  });

  it.each([
    '853296cc-eb78-4a6c-b747-cd5417473cc5',
    'd860ab28-db10-40dc-8775-ae00eeb21f23',
  ])('%s builds all 12 subagents, 4 at depth 1 and 8 at depth 2, none parked', async (id) => {
    const result = await graftSession(join(SLUG_DIR, `${id}.jsonl`));
    if (!result.ok) throw new Error(`refused: ${result.mismatch.code} ${result.mismatch.reason}`);
    const subagents = agentsIn(result.snapshot.root).filter((a) => a.kind === 'subagent');
    expect(subagents).toHaveLength(12);
    expect(subagents.filter((a) => a.spawnDepth === 1)).toHaveLength(4);
    expect(subagents.filter((a) => a.spawnDepth === 2)).toHaveLength(8);
    // Each depth-1 agent carries its own two, by the sidecar join.
    for (const parent of subagents.filter((a) => a.spawnDepth === 1)) {
      expect(agentsIn(parent).filter((a) => a.spawnDepth === 2), parent.id).toHaveLength(2);
    }
    expect(result.snapshot.parked).toEqual([]);
    expect(result.diagnostics.malformedLines).toBe(0);
  });

  it('every session matches its committed golden', async () => {
    for (const id of await sessionIds()) {
      const result = await graftSession(join(SLUG_DIR, `${id}.jsonl`));
      if (!result.ok) throw new Error(`${id} refused: ${result.mismatch.code}`);
      const produced = goldenText(result.snapshot);
      const goldenPath = join(GOLDEN_DIR, `${id}.json`);
      if (UPDATE_GOLDENS) {
        await writeFile(goldenPath, produced, 'utf8');
        continue;
      }
      const committed = await readFile(goldenPath, 'utf8');
      expect(committed.split('\r\n').join('\n'), `golden mismatch for ${id}`).toBe(produced);
    }
  });

  it('the golden directory holds exactly one golden per session, plus its README', async () => {
    if (UPDATE_GOLDENS) return;
    const names = (await readdir(GOLDEN_DIR)).sort();
    expect(names).toEqual([...(await sessionIds()).map((id) => `${id}.json`), 'README.md'].sort());
    expect(names).toHaveLength(3);
  });
});

describe('cost-state: a record type first observed on 2.1.283', () => {
  const COST_STATE_KEYS = [
    'hasUnknownModelCost',
    'modelUsage',
    'sessionId',
    'startTime',
    'totalAPIDuration',
    'totalAPIDurationWithoutRetries',
    'totalCostUSD',
    'totalDuration',
    'totalLinesAdded',
    'totalLinesRemoved',
    'totalToolDuration',
    'type',
  ];

  it('3 lines, all in main transcripts, every one with exactly the observed keys', async () => {
    const found: { main: boolean; keys: string[] }[] = [];
    for (const file of await transcripts()) {
      for (const line of await linesOf(file.path)) {
        const entry = JSON.parse(line) as Record<string, unknown>;
        if (entry['type'] === 'cost-state') {
          found.push({ main: file.main, keys: Object.keys(entry).sort() });
        }
      }
    }
    expect(found).toHaveLength(3);
    for (const hit of found) {
      expect(hit.main).toBe(true);
      expect(hit.keys).toEqual(COST_STATE_KEYS);
    }
  });

  it('is recognised and ignored, never malformed', async () => {
    expect(KNOWN_ENTRY_TYPES.has('cost-state')).toBe(false);
    expect(IGNORED_ENTRY_TYPES.has('cost-state')).toBe(true);
    let ignored = 0;
    for (const file of await transcripts()) {
      const lines = await linesOf(file.path);
      const batch = parseLines(lines);
      if (!batch.ok) throw new Error('parseLines reported ok:false, which it never does');
      expect(batch.diagnostics.malformedLines, file.path).toBe(0);
      ignored += batch.value.rejections.filter(
        (r) => r.rejection === 'ignoredType' && r.reason === 'ignored type: cost-state',
      ).length;
    }
    expect(ignored).toBe(3);
  });

  it('appears in no earlier corpus', async () => {
    for (const dir of await olderCorpora()) {
      for (const path of await jsonlUnder(dir)) {
        expect((await readFile(path, 'utf8')).includes('"type":"cost-state"'), path).toBe(false);
      }
    }
  });
});

describe('keys first observed on 2.1.283, pinned as observed', () => {
  /*
   * Counts are of this corpus as committed, which does not change. None of
   * these keys is required by the fingerprint or read by the model; the pin
   * is that they exist, how often, and that no earlier corpus carries them on
   * the same record type — so a re-harvest that loses or renames one is a
   * diff somebody reads rather than a silence.
   */
  const OBSERVED: Record<string, Record<string, number>> = {
    user: { turnOrigin: 2, serverClassifierContext: 74 },
    attachment: { rendered: 399, renderedInHumanTurn: 2 },
    assistant: {
      serverClassifierRequest: 153,
      advisorModel: 153,
      perTurnEffort: 153,
      wireToolInputs: 114,
      wireIngestContext: 3,
    },
  };

  it('entry keys: present at the observed counts', async () => {
    const counts: Record<string, Record<string, number>> = {};
    for (const file of await transcripts()) {
      for (const line of await linesOf(file.path)) {
        const entry = JSON.parse(line) as Record<string, unknown>;
        const type = String(entry['type']);
        const wanted = OBSERVED[type];
        if (wanted === undefined) continue;
        for (const key of Object.keys(wanted)) {
          if (key in entry) {
            counts[type] ??= {};
            counts[type][key] = (counts[type][key] ?? 0) + 1;
          }
        }
      }
    }
    expect(counts).toEqual(OBSERVED);
  });

  it('entry keys: absent from the same record type in every earlier corpus', async () => {
    for (const dir of await olderCorpora()) {
      for (const path of await jsonlUnder(dir)) {
        for (const line of await linesOf(path)) {
          let entry: Record<string, unknown>;
          try {
            entry = JSON.parse(line) as Record<string, unknown>;
          } catch {
            continue;
          }
          const wanted = OBSERVED[String(entry['type'])];
          if (wanted === undefined) continue;
          for (const key of Object.keys(wanted)) expect(key in entry, `${key} in ${path}`).toBe(false);
        }
      }
    }
  });

  it('sidecar keys: requestShape and requestNonInteractive on all 24, accepted and preserved', async () => {
    const shapes: Record<string, number> = {};
    let sidecars = 0;
    for (const id of await sessionIds()) {
      const fp = await fingerprintSession(join(SLUG_DIR, `${id}.jsonl`));
      if (!fp.ok) throw new Error(`${id} refused: ${fp.mismatch.code}`);
      for (const sub of fp.value.subagents) {
        sidecars += 1;
        const meta = sub.meta as unknown as Record<string, unknown>;
        expect(meta['requestNonInteractive'], sub.agentId).toBe(true);
        const shape = String(meta['requestShape']);
        shapes[shape] = (shapes[shape] ?? 0) + 1;
      }
    }
    expect(sidecars).toBe(24);
    expect(shapes).toEqual({ foreground: 22, background: 2 });
  });
});

/** Every committed `cc-2.1.<n>` corpus other than this one. */
async function olderCorpora(): Promise<string[]> {
  const dirs = (await readdir(FIXTURES))
    .filter((name) => /^cc-2\.1\.\d+$/.test(name) && name !== 'cc-2.1.283')
    .map((name) => join(FIXTURES, name));
  // A filter that matched nothing would make both "absent" tests vacuous.
  expect(dirs.length).toBeGreaterThanOrEqual(6);
  return dirs;
}

async function jsonlUnder(dir: string): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await readdir(dir, { withFileTypes: true, recursive: true })) {
    if (entry.isFile() && entry.name.endsWith('.jsonl')) out.push(join(entry.parentPath, entry.name));
  }
  return out;
}
