/**
 * Tests for the tree grafter.
 *
 * Three fixture trees are used and never mixed up:
 *
 *   fixtures/cc-2.1.234/        captured from real CC 2.1.234 sessions. Ground
 *                               truth: if the grafter refuses or mis-shapes
 *                               anything here, the grafter is wrong (G6).
 *   fixtures/synthetic-graft/   hand-made join-key corruption. Evidence about
 *                               *our* behaviour, never about CC's.
 *   fixtures/synthetic-layout/  hand-made layout corruption, used here only to
 *                               prove a fingerprint refusal yields NO tree.
 *
 * The captured session set is derived from the directory, never hard-coded:
 * a count pinned to today's harvest breaks on the next one and reads as a
 * regression rather than as new data.
 *
 * Golden snapshots live in `fixtures/golden/graft/`. They are regenerated by
 * running this file with `AGENT_DECK_UPDATE_GOLDENS=1`; see that directory's
 * README. Nothing is written without that variable set.
 */

import { createHash } from 'node:crypto';
import { readdirSync } from 'node:fs';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import type { AgentNode, SubagentMeta, TranscriptEntry, TreeNode } from './events.js';
import { isAgentNode } from './events.js';
import type { GraftSnapshot, SidecarArrival, TranscriptBatch } from './graft.js';
import {
  DEFAULT_PREVIEW_BYTES,
  MIN_PARSE_CEILING_BYTES,
  ROOT_NODE_ID,
  TreeGrafter,
  agentNodes,
  findNode,
  goldenText,
  graftSession,
  serializeSnapshot,
  toSessionState,
  walk,
} from './graft.js';
import { splitTranscript } from '../parser/attribution.js';
import { hydratePersistedOutputs, parseLines, parseSubagentMeta } from '../parser/parse.js';
import { TRUNCATION_MARKER_RE } from '../parser/redact.js';

// ---------------------------------------------------------------------------
// Fixture roots
// ---------------------------------------------------------------------------

const CAPTURED_ROOT = fileURLToPath(new URL('../../fixtures/cc-2.1.234/projects', import.meta.url));

/**
 * The captured project-slug directory, DERIVED from the projects root.
 *
 * The slug is a capture artefact like every session id: it encodes the
 * absolute path of the machine that recorded it, and on Windows even its
 * drive-letter case varies (`c--Users-…` and `C--Users-…` both occur in real
 * data). Spelling it out here would make this suite fail with ENOENT on the
 * next harvest, which reads as a grafter bug and is not one.
 *
 * Resolved eagerly and synchronously so `CAPTURED_SLUG` stays a plain
 * constant. Exactly one slug is required: more than one is a real ambiguity
 * about which capture these tests are about, and picking the first would be a
 * guess.
 */
const CAPTURED_SLUG = ((): string => {
  const slugs = readdirSync(CAPTURED_ROOT, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
  if (slugs.length !== 1) {
    throw new Error(
      `expected exactly one project-slug directory under\n${CAPTURED_ROOT}\nbut found ` +
        `${slugs.length}: [${slugs.join(', ')}].\nThis is a fixture-layout change, not a grafter ` +
        `bug: these tests are written against a single captured slug. Point them at one, or teach ` +
        `them to iterate.`,
    );
  }
  return join(CAPTURED_ROOT, slugs[0] as string);
})();

const GRAFT_ROOT = fileURLToPath(new URL('../../fixtures/synthetic-graft', import.meta.url));
const LAYOUT_ROOT = fileURLToPath(new URL('../../fixtures/synthetic-layout', import.meta.url));
const SYNTHETIC_SLUG = 'SYNTHETIC-hand-mutated-not-captured';
const GRAFT_SESSION = 'deadbeef-0000-4000-8000-0000000000a1';
const LAYOUT_SESSION = 'deadbeef-0000-4000-8000-000000000001';

const GOLDEN_DIR = fileURLToPath(new URL('../../fixtures/golden/graft', import.meta.url));
const UPDATE_GOLDENS = process.env['AGENT_DECK_UPDATE_GOLDENS'] === '1';

function graftMain(caseName: string): string {
  return join(GRAFT_ROOT, caseName, SYNTHETIC_SLUG, `${GRAFT_SESSION}.jsonl`);
}

function layoutMain(caseName: string): string {
  return join(LAYOUT_ROOT, caseName, SYNTHETIC_SLUG, `${LAYOUT_SESSION}.jsonl`);
}

/** Session ids in the captured slug, derived from the files on disk. */
async function capturedSessionIds(): Promise<string[]> {
  const names = await readdir(CAPTURED_SLUG, { withFileTypes: true });
  return names
    .filter((e) => e.isFile() && e.name.endsWith('.jsonl'))
    .map((e) => e.name.replace(/\.jsonl$/, ''))
    .sort();
}

// ---------------------------------------------------------------------------
// Fixture selection BY PROPERTY, never by literal id
// ---------------------------------------------------------------------------

/**
 * Everything a test needs to pick its subject without naming a session.
 *
 * Session ids, agent ids and `tool_use` ids are all capture artefacts: they
 * change on every harvest. A test that names one breaks with ENOENT (or a
 * silent `undefined`) the next time the fixtures are re-captured, which reads
 * as a grafter bug and is not one. Every test below therefore states the
 * PROPERTY it needs — "a session with a nested spawn", "a session with an
 * offloaded payload" — and {@link sessionWhere} finds it or explains exactly
 * what is missing.
 */
interface CapturedSession {
  sessionId: string;
  mainTranscript: string;
  /** Sidecars in the session's `subagents/` directory, parsed where possible. */
  sidecars: { agentId: string; transcriptPath: string; meta?: SubagentMeta }[];
  /** Absolute paths of `tool-results/*` payloads. Empty when there are none. */
  toolResultFiles: string[];
  /** Distinct `tool_use` ids across the main transcript and every subagent file. */
  toolUseIds: string[];
}

let capturedCache: Promise<CapturedSession[]> | undefined;

async function readEntries(path: string): Promise<TranscriptEntry[]> {
  const batch = parseLines(splitTranscript(await readFile(path, 'utf8')));
  return batch.ok ? batch.value.entries : [];
}

function toolUseIdsIn(entries: readonly TranscriptEntry[]): string[] {
  const ids: string[] = [];
  for (const entry of entries) {
    const message = entry['message'];
    if (typeof message !== 'object' || message === null) continue;
    const content = (message as { content?: unknown }).content;
    if (!Array.isArray(content)) continue;
    for (const block of content) {
      if (typeof block !== 'object' || block === null) continue;
      const b = block as { type?: unknown; id?: unknown };
      if (b.type === 'tool_use' && typeof b.id === 'string' && b.id !== '') ids.push(b.id);
    }
  }
  return ids;
}

/** Scan the captured slug once per test file. Read-only. */
async function capturedSessions(): Promise<CapturedSession[]> {
  capturedCache ??= (async () => {
    const out: CapturedSession[] = [];
    const names = await readdir(CAPTURED_SLUG, { withFileTypes: true });
    for (const entry of names) {
      if (!entry.isFile() || !entry.name.endsWith('.jsonl')) continue;
      const sessionId = entry.name.replace(/\.jsonl$/, '');
      const mainTranscript = join(CAPTURED_SLUG, entry.name);
      const sessionDir = join(CAPTURED_SLUG, sessionId);

      const ids = new Set(toolUseIdsIn(await readEntries(mainTranscript)));
      const sidecars: CapturedSession['sidecars'] = [];
      let subagentNames: string[] = [];
      try {
        subagentNames = (await readdir(join(sessionDir, 'subagents'))).sort();
      } catch {
        subagentNames = [];
      }
      for (const name of subagentNames) {
        const match = /^agent-(.+)\.jsonl$/.exec(name);
        if (match === null) continue;
        const agentId = match[1] as string;
        const transcriptPath = join(sessionDir, 'subagents', name);
        for (const id of toolUseIdsIn(await readEntries(transcriptPath))) ids.add(id);
        const record: CapturedSession['sidecars'][number] = { agentId, transcriptPath };
        try {
          const parsed = parseSubagentMeta(
            await readFile(join(sessionDir, 'subagents', `agent-${agentId}.meta.json`), 'utf8'),
          );
          if (parsed.ok) record.meta = parsed.value;
        } catch {
          // An unreadable sidecar simply carries no meta; selection predicates
          // treat it as not having whatever property they are looking for.
        }
        sidecars.push(record);
      }

      let toolResultFiles: string[] = [];
      try {
        toolResultFiles = (await readdir(join(sessionDir, 'tool-results')))
          .sort()
          .map((n) => join(sessionDir, 'tool-results', n));
      } catch {
        toolResultFiles = [];
      }

      out.push({
        sessionId,
        mainTranscript,
        sidecars,
        toolResultFiles,
        toolUseIds: [...ids].sort(),
      });
    }
    out.sort((a, b) => a.sessionId.localeCompare(b.sessionId));
    return out;
  })();
  return capturedCache;
}

function describeCaptured(session: CapturedSession): string {
  const depths = session.sidecars.map((s) => s.meta?.spawnDepth ?? -1);
  return `${session.sessionId} (sidecars=${session.sidecars.length} spawnDepths=[${depths.join(',')}] toolUses=${session.toolUseIds.length} toolResults=${session.toolResultFiles.length})`;
}

/**
 * The captured session with `property`, or a failure that says which property
 * is missing and what the capture actually contains.
 *
 * The diagnostic matters more than the lookup: an ENOENT on a hard-coded
 * session id looks like the grafter cannot open a file. This says, in one
 * line, that the fixtures moved and the test lost its subject.
 */
async function sessionWhere(
  property: string,
  predicate: (session: CapturedSession) => boolean,
): Promise<CapturedSession> {
  const sessions = await capturedSessions();
  const chosen = sessions.filter(predicate)[0];
  if (chosen === undefined) {
    throw new Error(
      `no captured session has ${property}.\n` +
        `This is a stale fixture reference, not a grafter bug: the capture under\n` +
        `${CAPTURED_SLUG}\n` +
        `was re-harvested and this test lost its subject. Scanned ${sessions.length} session(s):\n` +
        sessions.map((s) => `  - ${describeCaptured(s)}`).join('\n') +
        `\nEither capture a session with that property, or retire the test.`,
    );
  }
  return chosen;
}

/** The sidecar of an agent that some other agent spawned (`spawnDepth >= 2`). */
function nestedSidecarOf(
  session: CapturedSession,
): { agentId: string; meta: SubagentMeta } | undefined {
  for (const sidecar of session.sidecars) {
    const meta = sidecar.meta;
    if (meta === undefined) continue;
    if (meta.spawnDepth >= 2) return { agentId: sidecar.agentId, meta };
  }
  return undefined;
}

/**
 * Token usage a captured transcript states more than once for one message.
 *
 * `naiveOut` and `dedupedOut` are the two candidate aggregation rules applied
 * to the SAME lines: sum every line, versus sum the maximum per `message.id`.
 * The selector only returns a subject where the two disagree, so a test using
 * it pins a choice between two real numbers instead of restating the
 * production rule to itself.
 */
interface RepeatedUsageSubject {
  mainTranscript: string;
  /** Node id in the grafted tree: an agent id, or `ROOT_NODE_ID` for the main file. */
  agentId: string;
  /** The `message.id` that appears on more than one line with differing usage. */
  repeatedMessageId: string;
  naiveOut: number;
  dedupedOut: number;
  dedupedIn: number;
}

interface UsageLine {
  messageId: string;
  in: number;
  out: number;
}

function usageLinesIn(entries: readonly TranscriptEntry[]): UsageLine[] {
  const lines: UsageLine[] = [];
  for (const entry of entries) {
    const message = entry['message'];
    if (typeof message !== 'object' || message === null) continue;
    const m = message as { id?: unknown; usage?: unknown };
    if (typeof m.id !== 'string' || typeof m.usage !== 'object' || m.usage === null) continue;
    const u = m.usage as {
      input_tokens?: unknown;
      cache_creation_input_tokens?: unknown;
      cache_read_input_tokens?: unknown;
      output_tokens?: unknown;
    };
    // All three components, like production: `input_tokens` alone is 2 on
    // every real assistant message in this corpus. Reimplemented here rather
    // than imported so the test can disagree with the module it checks.
    const num = (v: unknown): number => (typeof v === 'number' && Number.isFinite(v) ? v : 0);
    lines.push({
      messageId: m.id,
      in:
        num(u.input_tokens) +
        num(u.cache_creation_input_tokens) +
        num(u.cache_read_input_tokens),
      out: num(u.output_tokens),
    });
  }
  return lines;
}

/** `undefined` unless some `message.id` occurs twice with different `output_tokens`. */
function repeatedUsageMessageId(lines: readonly UsageLine[]): string | undefined {
  const seen = new Map<string, Set<number>>();
  for (const line of lines) {
    const values = seen.get(line.messageId);
    if (values === undefined) seen.set(line.messageId, new Set([line.out]));
    else values.add(line.out);
  }
  for (const [messageId, values] of seen) if (values.size > 1) return messageId;
  return undefined;
}

/**
 * A captured transcript whose streamed message usage is restated per content
 * block, chosen by that property rather than by agent id.
 *
 * Subagent transcripts are tried before the main one only because they are
 * shorter and make a failure easier to read; either would serve. The search is
 * deterministic: sessions and agents are both scanned in sorted order.
 */
async function agentWithRepeatedUsage(): Promise<RepeatedUsageSubject> {
  const sessions = await capturedSessions();
  for (const session of sessions) {
    const candidates: { agentId: string; path: string }[] = [
      ...session.sidecars.map((s) => ({ agentId: s.agentId, path: s.transcriptPath })),
      { agentId: ROOT_NODE_ID, path: session.mainTranscript },
    ];
    for (const candidate of candidates) {
      const lines = usageLinesIn(await readEntries(candidate.path));
      const repeatedMessageId = repeatedUsageMessageId(lines);
      if (repeatedMessageId === undefined) continue;

      const maxima = new Map<string, { in: number; out: number }>();
      let naiveOut = 0;
      for (const line of lines) {
        naiveOut += line.out;
        const prev = maxima.get(line.messageId);
        maxima.set(line.messageId, {
          in: prev === undefined ? line.in : Math.max(prev.in, line.in),
          out: prev === undefined ? line.out : Math.max(prev.out, line.out),
        });
      }
      let dedupedOut = 0;
      let dedupedIn = 0;
      for (const value of maxima.values()) {
        dedupedOut += value.out;
        dedupedIn += value.in;
      }

      return {
        mainTranscript: session.mainTranscript,
        agentId: candidate.agentId,
        repeatedMessageId,
        naiveOut,
        dedupedOut,
        dedupedIn,
      };
    }
  }
  throw new Error(
    'no captured transcript restates one `message.id` across lines with differing ' +
      '`output_tokens`.\nThis is a stale fixture reference, not a grafter bug: the capture under\n' +
      `${CAPTURED_SLUG}\n` +
      'was re-harvested and this test lost its subject. Without such a transcript the two ' +
      'aggregation rules (sum every line, versus sum the maximum per message) agree and there ' +
      `is nothing left to pin. Scanned ${sessions.length} session(s):\n` +
      sessions.map((s) => `  - ${describeCaptured(s)}`).join('\n'),
  );
}

// ---------------------------------------------------------------------------
// A replayable session: every file read once, then fed in whatever order a
// test wants. Deliberately independent of `graftSession`'s ordering so an
// out-of-order test cannot accidentally be testing the in-order path.
// ---------------------------------------------------------------------------

interface ReplayFile {
  batch: TranscriptBatch;
  /** Parsed entries, whole file. Tests slice this to simulate a partial tail. */
  entries: TranscriptEntry[];
}

interface ReplaySession {
  sessionId: string;
  projectSlug: string;
  mainPath: string;
  main: ReplayFile;
  agents: ReplayFile[];
  sidecars: SidecarArrival[];
  /** `tool_use` id -> redacted offloaded payload, already resolved from disk. */
  payloads: Map<string, string>;
}

async function loadReplay(mainTranscript: string): Promise<ReplaySession> {
  const slugDir = dirname(mainTranscript);
  const sessionId = basename(mainTranscript).replace(/\.jsonl$/, '');
  const sessionDir = join(slugDir, sessionId);

  const readEntries = async (path: string): Promise<TranscriptEntry[]> => {
    const text = await readFile(path, 'utf8');
    const batch = parseLines(splitTranscript(text));
    return batch.ok ? batch.value.entries : [];
  };

  const mainEntries = await readEntries(mainTranscript);
  const main: ReplayFile = {
    batch: { kind: 'main', path: mainTranscript, entries: mainEntries },
    entries: mainEntries,
  };

  const agents: ReplayFile[] = [];
  const sidecars: SidecarArrival[] = [];
  let subagentNames: string[] = [];
  try {
    subagentNames = (await readdir(join(sessionDir, 'subagents'))).sort();
  } catch {
    subagentNames = [];
  }
  for (const name of subagentNames) {
    const match = /^agent-(.+)\.jsonl$/.exec(name);
    if (match === null) continue;
    const agentId = match[1] as string;
    const transcriptPath = join(sessionDir, 'subagents', name);
    const entries = await readEntries(transcriptPath);
    agents.push({
      batch: { kind: 'subagent', path: transcriptPath, agentId, entries },
      entries,
    });
    const metaPath = join(sessionDir, 'subagents', `agent-${agentId}.meta.json`);
    const arrival: SidecarArrival = { agentId, metaPath };
    try {
      const parsed = parseSubagentMeta(await readFile(metaPath, 'utf8'), metaPath);
      if (parsed.ok) arrival.meta = parsed.value;
      else arrival.metaFailure = parsed.mismatch.reason;
    } catch (error: unknown) {
      arrival.metaFailure = error instanceof Error ? error.message : String(error);
    }
    sidecars.push(arrival);
  }

  const payloads = new Map<string, string>();
  for (const file of [main, ...agents]) {
    for (const entry of file.entries) {
      const hydrated = await hydratePersistedOutputs(entry, {
        projectsRoot: dirname(slugDir),
        slug: basename(slugDir),
        sessionId,
      });
      for (const item of hydrated) {
        if (item.toolUseId !== '') payloads.set(item.toolUseId, item.read.text);
      }
    }
  }

  return {
    sessionId,
    projectSlug: basename(slugDir),
    mainPath: mainTranscript,
    main,
    agents,
    sidecars,
    payloads,
  };
}

/** A single step of a replay script. */
type Step =
  | { kind: 'main'; upTo?: number }
  | { kind: 'agent'; agentId: string; upTo?: number }
  | { kind: 'sidecar'; agentId: string }
  | { kind: 'payloads' };

function newGrafter(session: ReplaySession): TreeGrafter {
  return new TreeGrafter({ sessionId: session.sessionId, projectSlug: session.projectSlug });
}

function apply(grafter: TreeGrafter, session: ReplaySession, step: Step): void {
  switch (step.kind) {
    case 'main':
      grafter.addTranscript({
        ...session.main.batch,
        entries: session.main.entries.slice(0, step.upTo ?? session.main.entries.length),
      });
      return;
    case 'agent': {
      const file = session.agents.find((a) => a.batch.agentId === step.agentId);
      if (file === undefined) throw new Error(`no agent transcript ${step.agentId}`);
      grafter.addTranscript({
        ...file.batch,
        entries: file.entries.slice(0, step.upTo ?? file.entries.length),
      });
      return;
    }
    case 'sidecar': {
      const sidecar = session.sidecars.find((s) => s.agentId === step.agentId);
      if (sidecar === undefined) throw new Error(`no sidecar ${step.agentId}`);
      grafter.addSidecar(sidecar);
      return;
    }
    case 'payloads':
      for (const [toolUseId, text] of session.payloads) {
        grafter.addToolResultPayload(toolUseId, text);
      }
      return;
  }
}

/** Everything, in file order: main, then each agent, then each sidecar, then payloads. */
function inOrderScript(session: ReplaySession): Step[] {
  return [
    { kind: 'main' },
    ...session.agents.map((a): Step => ({ kind: 'agent', agentId: a.batch.agentId as string })),
    ...session.sidecars.map((s): Step => ({ kind: 'sidecar', agentId: s.agentId })),
    { kind: 'payloads' },
  ];
}

function replay(session: ReplaySession, script: Step[]): GraftSnapshot {
  const grafter = newGrafter(session);
  for (const step of script) apply(grafter, session, step);
  return grafter.snapshot();
}

// ---------------------------------------------------------------------------
// Small assertions helpers
// ---------------------------------------------------------------------------

function parkedCodes(snapshot: GraftSnapshot): Record<string, string> {
  const out: Record<string, string> = {};
  for (const p of snapshot.parked) out[p.agentId] = p.code;
  return out;
}

function graftedAgentIds(snapshot: GraftSnapshot): string[] {
  return agentNodes(snapshot.root)
    .filter((n) => n.id !== ROOT_NODE_ID)
    .map((n) => n.id)
    .sort();
}

function childAgentIds(node: AgentNode): string[] {
  return node.children
    .filter((c): c is AgentNode => isAgentNode(c))
    .map((c) => c.id)
    .sort();
}

async function fileDigests(root: string): Promise<Record<string, string>> {
  const out: Record<string, string> = {};
  const visit = async (dir: string): Promise<void> => {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        await visit(full);
        continue;
      }
      out[full.slice(root.length + 1).split('\\').join('/')] = createHash('sha256')
        .update(await readFile(full))
        .digest('hex');
    }
  };
  await visit(root);
  return out;
}

// ---------------------------------------------------------------------------
// Golden snapshots
// ---------------------------------------------------------------------------

describe('captured sessions graft to their committed golden snapshots', () => {
  it('every session transcript in the captured slug has a golden and matches it', async () => {
    const sessionIds = await capturedSessionIds();
    // Derived, not pinned: a re-harvest adds sessions rather than failing here.
    expect(sessionIds.length).toBeGreaterThan(0);

    for (const sessionId of sessionIds) {
      const result = await graftSession(join(CAPTURED_SLUG, `${sessionId}.jsonl`));
      if (!result.ok) throw new Error(`captured session ${sessionId} refused: ${result.mismatch.code}`);
      const produced = goldenText(result.snapshot);
      const goldenPath = join(GOLDEN_DIR, `${sessionId}.json`);
      if (UPDATE_GOLDENS) {
        await writeFile(goldenPath, produced, 'utf8');
        continue;
      }
      const committed = await readFile(goldenPath, 'utf8');
      expect(committed.split('\r\n').join('\n'), `golden mismatch for ${sessionId}`).toBe(produced);
    }
  });

  it('the golden directory holds exactly one golden per captured session', async () => {
    if (UPDATE_GOLDENS) return;
    const sessionIds = await capturedSessionIds();
    const goldens = (await readdir(GOLDEN_DIR))
      .filter((n) => n.endsWith('.json'))
      .map((n) => n.replace(/\.json$/, ''))
      .sort();
    expect(goldens).toEqual(sessionIds);
  });

  it('a golden is stable across repeated grafts of the same input', async () => {
    const main = join(CAPTURED_SLUG, `${(await capturedSessionIds())[0] as string}.jsonl`);
    const a = await graftSession(main);
    const b = await graftSession(main);
    if (!a.ok || !b.ok) throw new Error('captured session must graft');
    expect(goldenText(a.snapshot)).toBe(goldenText(b.snapshot));
  });

  it('grafting the captured tree leaves every fixture byte-identical (G1)', async () => {
    const before = await fileDigests(CAPTURED_ROOT);
    for (const sessionId of await capturedSessionIds()) {
      await graftSession(join(CAPTURED_SLUG, `${sessionId}.jsonl`));
    }
    expect(await fileDigests(CAPTURED_ROOT)).toEqual(before);
  });

  it('a manual in-order replay reproduces graftSession exactly', async () => {
    for (const sessionId of await capturedSessionIds()) {
      const main = join(CAPTURED_SLUG, `${sessionId}.jsonl`);
      const loaded = await graftSession(main);
      if (!loaded.ok) throw new Error('captured session must graft');
      const session = await loadReplay(main);
      const manual = replay(session, inOrderScript(session));
      expect(goldenText(manual), sessionId).toBe(goldenText(loaded.snapshot));
    }
  });
});

// ---------------------------------------------------------------------------
// Shape of the captured trees
// ---------------------------------------------------------------------------

describe('captured topology', () => {
  it('grafts every captured sidecar: 0 parked across the whole capture', async () => {
    let grafted = 0;
    let parked = 0;
    for (const sessionId of await capturedSessionIds()) {
      const result = await graftSession(join(CAPTURED_SLUG, `${sessionId}.jsonl`));
      if (!result.ok) throw new Error(`refused ${sessionId}`);
      grafted += result.snapshot.counts.grafted;
      parked += result.snapshot.counts.parked;
      expect(result.snapshot.parked, sessionId).toEqual([]);
    }
    // Derived from the capture, not pinned: every sidecar on disk grafts.
    const expectedAgents = await countCapturedSidecars();
    expect(grafted).toBe(expectedAgents);
    expect(parked).toBe(0);
  });

  it('a depth-2 agent grafts onto its parent AGENT, never onto the root', async () => {
    let checked = 0;
    for (const sessionId of await capturedSessionIds()) {
      const result = await graftSession(join(CAPTURED_SLUG, `${sessionId}.jsonl`));
      if (!result.ok) throw new Error(`refused ${sessionId}`);
      const deep = result.snapshot.edges.filter((e) => e.depth >= 2);
      for (const edge of deep) {
        checked++;
        expect(edge.parentNodeId).not.toBe(ROOT_NODE_ID);
        // The parent node id is an agent that is itself in the tree...
        const parent = findNode(result.snapshot.root, edge.parentNodeId);
        expect(parent, `parent ${edge.parentNodeId} must be in the tree`).toBeDefined();
        expect(parent !== undefined && isAgentNode(parent)).toBe(true);
        // ...and the child is among ITS children, not the root's.
        expect(childAgentIds(parent as AgentNode)).toContain(edge.agentId);
        expect(childAgentIds(result.snapshot.root)).not.toContain(edge.agentId);
        // The sidecar's own spawnDepth agrees with the walked depth.
        expect(edge.recordedDepth).toBe(edge.depth);
      }
    }
    // The capture contains at least one nested spawn; if a re-harvest drops it
    // this test says so instead of quietly passing on an empty set.
    expect(checked).toBeGreaterThan(0);
  });

  it('every graft edge names a tool_use id that exists as a ToolNode in the parent', async () => {
    for (const sessionId of await capturedSessionIds()) {
      const result = await graftSession(join(CAPTURED_SLUG, `${sessionId}.jsonl`));
      if (!result.ok) throw new Error(`refused ${sessionId}`);
      for (const edge of result.snapshot.edges) {
        const parent = findNode(result.snapshot.root, edge.parentNodeId);
        expect(parent).toBeDefined();
        const tools = (parent as AgentNode).children.filter((c) => !isAgentNode(c));
        expect(tools.map((t) => t.id)).toContain(edge.toolUseId);
      }
    }
  });

  it('the spawning tool is named Agent, and no Task tool exists (Phase 0 verdict)', async () => {
    const names = new Set<string>();
    const spawnNames = new Set<string>();
    for (const sessionId of await capturedSessionIds()) {
      const result = await graftSession(join(CAPTURED_SLUG, `${sessionId}.jsonl`));
      if (!result.ok) throw new Error(`refused ${sessionId}`);
      const spawnIds = new Set(result.snapshot.edges.map((e) => e.toolUseId));
      walk(result.snapshot.root, (node: TreeNode) => {
        if (isAgentNode(node)) return;
        names.add(node.toolName);
        if (spawnIds.has(node.id)) spawnNames.add(node.toolName);
      });
    }
    expect([...spawnNames]).toEqual(['Agent']);
    expect(names.has('Task')).toBe(false);
  });

  it('token totals de-duplicate the repeated per-block usage object', async () => {
    // CC writes one JSONL line per content block of a streamed assistant
    // message and repeats `message.usage` on every one of them, updated so
    // far. The subject is therefore chosen by that PROPERTY - a transcript
    // where one `message.id` appears on two or more lines carrying different
    // `output_tokens` - not by naming an agent a re-harvest can rename.
    const subject = await agentWithRepeatedUsage();
    const result = await graftSession(subject.mainTranscript);
    if (!result.ok) throw new Error(`captured session must graft: ${result.mismatch.code}`);
    const agent = findNode(result.snapshot.root, subject.agentId);
    expect(agent, `agent ${subject.agentId} must be in the tree`).toBeDefined();
    const node = agent as AgentNode;

    // The two candidate rules give different answers on this data, which is
    // the whole point: naive line-summing double-counts a streamed message.
    expect(subject.naiveOut).toBeGreaterThan(subject.dedupedOut);
    // `burn` is the de-duplicated SUM across distinct ids - the figure the old
    // `tokens` field held. `contextNow` is a level and is deliberately not
    // compared against a sum here.
    expect(node.burn?.output).toBe(subject.dedupedOut);
    expect(node.burn?.output).not.toBe(subject.naiveOut);
    expect(node.burn?.prompt).toBe(subject.dedupedIn);
  });

  it('the de-duplicated total matches the hand-measured capture', async () => {
    // The one place a captured literal is KEPT, deliberately. The test above
    // re-derives its expectation with the same rule the production code uses,
    // which cannot catch a rule that is wrong the same way twice. These
    // numbers were read off the fixture by hand instead:
    //
    //   agent-a1a53f42c5eca8824.jsonl lines 3 and 4 share
    //   msg_011CeBgYk4Ci1ZkTxynEZh3j with output_tokens 1 then 518; lines 6
    //   and 7 share msg_011CeBgfTGMFk39bxRHxoxen with 2 then 1099.
    //   Correct total 518 + 1099 = 1617. Naive line-sum would be 1620.
    //
    // If a re-harvest drops that agent this fails with the diagnostic from
    // `sessionWhere`, naming the property it needed - not with an ENOENT that
    // reads like a grafter bug.
    // RE-MEASURED for the token contract. `in: 2 + 2` was the literal defect
    // this release removes: `input_tokens` alone, on two messages. The prompt
    // is all three components per message, summed across distinct ids:
    //   msg_011CeBgYk4Ci1ZkTxynEZh3j  2 +  8054 + 18703 = 26759, out  518
    //   msg_011CeBgfTGMFk39bxRHxoxen  2 +  4008 + 26757 = 30767, out 1099
    const HAND_MEASURED = {
      agentId: 'a1a53f42c5eca8824',
      out: 518 + 1099,
      in: 2 + 8054 + 18703 + (2 + 4008 + 26757),
      // The LAST message by ordinal, which is a level rather than a total.
      contextNow: { prompt: 2 + 4008 + 26757, output: 1099 },
    };
    const session = await sessionWhere(
      `the hand-measured agent ${HAND_MEASURED.agentId}, whose token literals were read off that ` +
        `exact capture and mean nothing without it (see the comment on this test)`,
      (candidate) => candidate.sidecars.some((sidecar) => sidecar.agentId === HAND_MEASURED.agentId),
    );
    const result = await graftSession(session.mainTranscript);
    if (!result.ok) throw new Error(`captured session must graft: ${result.mismatch.code}`);
    const node = findNode(result.snapshot.root, HAND_MEASURED.agentId) as AgentNode | undefined;
    expect(node, `agent ${HAND_MEASURED.agentId} must be in the tree`).toBeDefined();
    expect(node?.burn?.output).toBe(HAND_MEASURED.out);
    expect(node?.burn?.prompt).toBe(HAND_MEASURED.in);
    expect(node?.burn?.prompt).toBe(57_526);
    expect(node?.contextNow).toStrictEqual(HAND_MEASURED.contextNow);
    // The old field read 4 for this agent. Nothing may report that again.
    expect(node?.burn?.prompt).not.toBe(4);
  });

  it('an offloaded tool-results payload reaches the node preview, redacted', async () => {
    const session = await sessionWhere(
      'a non-empty `tool-results/` directory (an offloaded tool payload)',
      (candidate) => candidate.toolResultFiles.length > 0,
    );
    const main = session.mainTranscript;
    const withHydration = await graftSession(main);
    const withoutHydration = await graftSession(main, { hydrateToolResults: false });
    if (!withHydration.ok || !withoutHydration.ok) throw new Error('must graft');
    // The stub says `<persisted-output>`; the hydrated preview does not.
    const stubbed = collectResultPreviews(withoutHydration.snapshot).filter((t) =>
      t.startsWith('<persisted-output>'),
    );
    expect(stubbed.length).toBeGreaterThan(0);
    const hydrated = collectResultPreviews(withHydration.snapshot).filter((t) =>
      t.startsWith('<persisted-output>'),
    );
    expect(hydrated).toEqual([]);
    // The hydrated preview really is the offloaded FILE's content, not the
    // stub's inline excerpt. Derived from the payload on disk rather than
    // pinned to a literal: read the payload and require some preview to start
    // with its own opening bytes.
    const payloadPath = session.toolResultFiles[0] as string;
    const payloadHead = (await readFile(payloadPath, 'utf8')).slice(0, 40);
    expect(payloadHead.length).toBeGreaterThan(0);
    expect(
      collectResultPreviews(withHydration.snapshot).some((t) => t.startsWith(payloadHead)),
      `no preview starts with the first 40 characters of ${payloadPath}`,
    ).toBe(true);

    // Every preview stays inside the byte ceiling. The truncation marker is an
    // annotation that sits ON TOP of the budget (see `truncationMarker`), so
    // the kept PAYLOAD is what the ceiling applies to.
    for (const text of collectResultPreviews(withHydration.snapshot)) {
      const marked = TRUNCATION_MARKER_RE.exec(text);
      if (marked === null) {
        expect(Buffer.byteLength(text, 'utf8')).toBeLessThanOrEqual(DEFAULT_PREVIEW_BYTES);
        continue;
      }
      expect(Number(marked[1])).toBeLessThanOrEqual(DEFAULT_PREVIEW_BYTES);
      expect(Buffer.byteLength(text.slice(0, text.length - marked[0].length), 'utf8')).toBeLessThanOrEqual(
        DEFAULT_PREVIEW_BYTES,
      );
    }
  });
});

// ---------------------------------------------------------------------------
// Phase 4 carry-forward A: one ceiling, and an honest marker
// ---------------------------------------------------------------------------

describe('previewBytes is the ceiling, and the marker states the ORIGINAL size', () => {
  /**
   * Both halves of the Phase 4 defect, asserted against the captured tree.
   *
   * Before the fix, measured across ALL 8 payloads over 8 KB in the capture
   * (7 inline, 1 offloaded — the offload path is one eighth of this, not the
   * scope of it):
   *
   *   previewBytes=8192    8 markers, every one of them "8192 of 8248"
   *   previewBytes=16384   8 markers, all "8192 of <real size>"
   *   previewBytes=65536   identical to 16384 — kept bytes never exceeded 8192
   *
   * (a) is "kept bytes must follow the setting above 8192"; (b) is "the second
   * number in the marker must be the payload's real size, not the length of an
   * already-marked string".
   *
   * Every number here is UTF-8 BYTES. `Buffer.byteLength` is used rather than
   * `String.length` throughout: the two differ on this very fixture (the
   * 512-byte preview of the offloaded payload is 567 bytes and 566 characters),
   * and an audit of this repo once produced a false accusation by comparing
   * the two as if they were one quantity.
   */

  /** Sizes on disk of every payload the capture holds that exceeds 8 KB. */
  async function payloadsOver8k(): Promise<number[]> {
    const sizes: number[] = [];
    for (const sessionId of await capturedSessionIds()) {
      const dir = join(CAPTURED_SLUG, sessionId, 'tool-results');
      let names: string[] = [];
      try {
        names = await readdir(dir);
      } catch {
        names = [];
      }
      for (const name of names) {
        const bytes = Buffer.byteLength(await readFile(join(dir, name), 'utf8'), 'utf8');
        if (bytes > 8192) sizes.push(bytes);
      }
      for (const file of [join(CAPTURED_SLUG, `${sessionId}.jsonl`), ...(await subagentFiles(sessionId))]) {
        for (const line of splitTranscript(await readFile(file, 'utf8'))) {
          for (const block of toolResultBlocks(line)) {
            const bytes = Buffer.byteLength(block, 'utf8');
            if (bytes > 8192) sizes.push(bytes);
          }
        }
      }
    }
    return sizes.sort((a, b) => b - a);
  }

  async function subagentFiles(sessionId: string): Promise<string[]> {
    const dir = join(CAPTURED_SLUG, sessionId, 'subagents');
    try {
      return (await readdir(dir)).filter((n) => n.endsWith('.jsonl')).map((n) => join(dir, n));
    } catch {
      return [];
    }
  }

  /** `tool_result` blocks whose content is a plain string, from one JSONL line. */
  function toolResultBlocks(line: string): string[] {
    let entry: unknown;
    try {
      entry = JSON.parse(line);
    } catch {
      return [];
    }
    const content = (entry as { message?: { content?: unknown } }).message?.content;
    if (!Array.isArray(content)) return [];
    const out: string[] = [];
    for (const block of content) {
      const b = block as { type?: unknown; content?: unknown };
      if (b.type === 'tool_result' && typeof b.content === 'string') out.push(b.content);
    }
    return out;
  }

  /** Every truncation marker in every preview of the whole capture, at one setting. */
  async function markersAt(previewBytes: number): Promise<{ kept: number; original: number }[]> {
    const out: { kept: number; original: number }[] = [];
    for (const sessionId of await capturedSessionIds()) {
      const result = await graftSession(join(CAPTURED_SLUG, `${sessionId}.jsonl`), { previewBytes });
      if (!result.ok) throw new Error(`captured session must graft: ${result.mismatch.code}`);
      walk(result.snapshot.root, (node) => {
        if (isAgentNode(node)) return;
        for (const text of [node.inputPreview, node.resultPreview]) {
          if (text === undefined) continue;
          const m = TRUNCATION_MARKER_RE.exec(text);
          if (m === null) continue;
          // The marker's kept count must MEASURE the payload beside it.
          const payload = text.slice(0, text.length - m[0].length);
          expect(Buffer.byteLength(payload, 'utf8')).toBe(Number(m[1]));
          out.push({ kept: Number(m[1]), original: Number(m[2]) });
        }
      });
    }
    return out;
  }

  it('(a) raising previewBytes above 8192 raises the kept bytes', async () => {
    const sizes = await payloadsOver8k();
    expect(sizes.length).toBeGreaterThan(0);
    const largest = sizes[0] as number;
    expect(largest).toBeGreaterThan(16384);

    const at8k = await markersAt(8192);
    const at16k = await markersAt(16384);
    expect(Math.max(...at8k.map((m) => m.kept))).toBe(8192);
    // The number that was stuck at 8192 before the fix.
    expect(Math.max(...at16k.map((m) => m.kept))).toBe(16384);

    // Fewer payloads are big enough to be cut at the higher ceiling, and none
    // is cut at a ceiling above its own size.
    expect(at16k.length).toBeLessThan(at8k.length);
    for (const m of at16k) expect(m.original).toBeGreaterThan(16384);
  });

  it('(a) a ceiling above the largest payload truncates nothing at all', async () => {
    const sizes = await payloadsOver8k();
    const ceiling = (sizes[0] as number) + 1024;
    const markers = await markersAt(ceiling);
    expect(markers).toEqual([]);
  });

  it('(b) at the shipped 8192 default every marker states the payload real size', async () => {
    const sizes = await payloadsOver8k();
    const markers = await markersAt(8192);
    expect(markers.length).toBeGreaterThan(0);
    for (const m of markers) {
      expect(m.kept).toBe(8192);
      // The old bug: 8192 + marker length. Named explicitly so a regression
      // cannot pass by being merely "some number bigger than kept".
      expect(m.original).not.toBe(8192 + '\n...[agent-deck: truncated, showing 8192 of 63774 bytes]'.length);
      expect(sizes).toContain(m.original);
    }
    // Every over-8-KB payload on disk is accounted for by a marker.
    expect([...markers.map((m) => m.original)].sort((a, b) => b - a)).toEqual(sizes);
  });

  it('(b) a preview ceiling BELOW the parse ceiling still names the original', async () => {
    const sizes = await payloadsOver8k();
    const markers = await markersAt(DEFAULT_PREVIEW_BYTES);
    expect(markers.length).toBeGreaterThan(0);
    for (const m of markers) {
      expect(m.kept).toBeLessThanOrEqual(DEFAULT_PREVIEW_BYTES);
      expect(m.original).toBeGreaterThan(m.kept);
    }
    // Payloads between 512 and 8192 bytes are also marked here and their
    // originals are their own sizes, so only the over-8-KB ones are compared
    // against the disk. Before the fix this set was eight copies of 8248 (the
    // length of the string the second pass was handed) rather than the eight
    // real sizes — which is exactly the equality below.
    expect(markers.map((m) => m.original).filter((n) => n > 8192).sort((a, b) => b - a)).toEqual(sizes);
  });

  it('a small previewBytes does not destroy the persisted-output stub (offload still hydrates)', async () => {
    // The stub is ~2.2 KB. Taking the PARSE ceiling down to previewBytes would
    // cut its closing tag off, `parsePersistedOutputPointer` would return
    // undefined, and the offloaded payload would never be read — a silent loss
    // of the whole G4 offload path. The parse ceiling is floored at 8 KB for
    // exactly this reason; this is the test that says so.
    const session = await sessionWhere(
      'a non-empty `tool-results/` directory (an offloaded tool payload)',
      (candidate) => candidate.toolResultFiles.length > 0,
    );
    const payload = await readFile(session.toolResultFiles[0] as string, 'utf8');
    const head = payload.slice(0, 40);
    for (const previewBytes of [128, DEFAULT_PREVIEW_BYTES, 8192]) {
      const result = await graftSession(session.mainTranscript, { previewBytes });
      if (!result.ok) throw new Error('must graft');
      const previews = collectResultPreviews(result.snapshot);
      expect(previews.filter((t) => t.startsWith('<persisted-output>')), `previewBytes=${previewBytes}`).toEqual([]);
      expect(
        previews.some((t) => t.startsWith(head)),
        `previewBytes=${previewBytes}: the offloaded payload did not reach a preview`,
      ).toBe(true);
    }
  });

  it('an explicit parse.maxPayloadBytes UNDER the floor is clamped, so offload still hydrates', async () => {
    // The escape hatch, closed. `previewBytes` was floored for the parse layer
    // but `parse.maxPayloadBytes` used to win outright, so a caller naming a
    // number below the floor got the whole G4 offload path silently switched
    // off. Measured through the production path before the clamp, at
    // previewBytes=512 on the offloaded 63,774-byte payload:
    //
    //   {previewBytes:512}                              "===== run.mjs =====…"
    //                                                    marker "512 of 63774"
    //   {previewBytes:512, parse:{maxPayloadBytes:512}} "<persisted-output>…"
    //                                                    marker "512 of 2186"
    //
    // All counts UTF-8 bytes.
    const session = await sessionWhere(
      'a non-empty `tool-results/` directory (an offloaded tool payload)',
      (candidate) => candidate.toolResultFiles.length > 0,
    );
    const offloaded = await readFile(session.toolResultFiles[0] as string, 'utf8');
    const head = offloaded.slice(0, 40);
    const offloadedBytes = Buffer.byteLength(offloaded, 'utf8');
    expect(offloadedBytes).toBeGreaterThan(MIN_PARSE_CEILING_BYTES);

    for (const maxPayloadBytes of [1, 512, MIN_PARSE_CEILING_BYTES - 1]) {
      const result = await graftSession(session.mainTranscript, {
        previewBytes: 512,
        parse: { maxPayloadBytes },
      });
      if (!result.ok) throw new Error('must graft');
      const previews = collectResultPreviews(result.snapshot);
      expect(
        previews.filter((t) => t.startsWith('<persisted-output>')),
        `parse.maxPayloadBytes=${maxPayloadBytes}: the stub reached a preview`,
      ).toEqual([]);
      const hydrated = previews.find((t) => t.startsWith(head));
      expect(
        hydrated,
        `parse.maxPayloadBytes=${maxPayloadBytes}: the offloaded payload did not reach a preview`,
      ).toBeTypeOf('string');
      // The marker must name the offloaded file's real size, never the stub's:
      // "512 of 2186" is what the unclamped hatch produced.
      const marker = TRUNCATION_MARKER_RE.exec(hydrated as string);
      expect(marker, `parse.maxPayloadBytes=${maxPayloadBytes}: preview was not marked`).not.toBeNull();
      expect(Number((marker as RegExpExecArray)[1])).toBe(512);
      expect(Number((marker as RegExpExecArray)[2])).toBe(offloadedBytes);
    }
  });

  it('an explicit parse.maxPayloadBytes ABOVE the floor is still honoured, and still double-cuts', async () => {
    // The clamp raises a low ceiling; it does not ignore the option. A ceiling
    // above the floor but below `previewBytes` is the caller's business and
    // still governs the kept bytes.
    const sizes = await payloadsOver8k();
    const largest = sizes[0] as number;
    expect(largest).toBeGreaterThan(16384);

    const ceiling = 16384;
    const markers: { kept: number; original: number }[] = [];
    for (const sessionId of await capturedSessionIds()) {
      const result = await graftSession(join(CAPTURED_SLUG, `${sessionId}.jsonl`), {
        previewBytes: largest + 1024,
        parse: { maxPayloadBytes: ceiling },
      });
      if (!result.ok) throw new Error('captured session must graft');
      walk(result.snapshot.root, (node) => {
        if (isAgentNode(node)) return;
        for (const text of [node.inputPreview, node.resultPreview]) {
          if (text === undefined) continue;
          const m = TRUNCATION_MARKER_RE.exec(text);
          if (m === null) continue;
          markers.push({ kept: Number(m[1]), original: Number(m[2]) });
        }
      });
    }
    // Cut by the explicit parse ceiling, not by the far larger preview ceiling
    // — which would have left the largest payload uncut entirely.
    expect(markers.length, 'no payload was cut at 16384').toBeGreaterThan(0);
    for (const m of markers) {
      expect(m.kept).toBeLessThanOrEqual(ceiling);
      expect(m.original).toBeGreaterThan(m.kept);
    }
    expect(Math.max(...markers.map((m) => m.kept))).toBe(ceiling);
    expect(markers.map((m) => m.original)).toContain(largest);
  });

  it('MIN_PARSE_CEILING_BYTES exceeds the persisted-output stub actually on disk', async () => {
    // The floor's whole justification is a size relationship with a string in
    // the fixtures, so the relationship is measured here rather than asserted
    // in a comment. Derived from the capture: a re-harvest with a longer stub
    // fails this test instead of silently disabling offload hydration.
    let largestStub = 0;
    for (const sessionId of await capturedSessionIds()) {
      for (const file of [join(CAPTURED_SLUG, `${sessionId}.jsonl`), ...(await subagentFiles(sessionId))]) {
        for (const line of splitTranscript(await readFile(file, 'utf8'))) {
          for (const block of toolResultBlocks(line)) {
            if (!block.startsWith('<persisted-output>')) continue;
            largestStub = Math.max(largestStub, Buffer.byteLength(block, 'utf8'));
          }
        }
      }
    }
    expect(largestStub).toBeGreaterThan(0);
    expect(MIN_PARSE_CEILING_BYTES).toBeGreaterThan(largestStub);
  });
});

function collectResultPreviews(snapshot: GraftSnapshot): string[] {
  const out: string[] = [];
  walk(snapshot.root, (node) => {
    if (isAgentNode(node)) return;
    if (node.resultPreview !== undefined) out.push(node.resultPreview);
  });
  return out;
}

async function countCapturedSidecars(): Promise<number> {
  let count = 0;
  for (const sessionId of await capturedSessionIds()) {
    try {
      const names = await readdir(join(CAPTURED_SLUG, sessionId, 'subagents'));
      count += names.filter((n) => n.endsWith('.meta.json')).length;
    } catch {
      // No subagents directory: a session with no subagents contributes 0.
    }
  }
  return count;
}

// ---------------------------------------------------------------------------
// Out-of-order arrival — the point of the component
// ---------------------------------------------------------------------------

describe('out-of-order arrival parks explicitly and re-joins on late data', () => {
  /**
   * The subject is "a captured session with a nested spawn", chosen by
   * property. These tests need depth >= 2 on real data: the transitive
   * `parentNotGrafted` park only exists when one agent's `tool_use` block
   * lives in another agent's transcript, and a flat session would let a
   * grafter that hoists orphans to the root pass every one of them.
   */
  const capturedMain = async (): Promise<string> =>
    (
      await sessionWhere(
        'a subagent at spawnDepth >= 2 (a nested spawn)',
        (candidate) => nestedSidecarOf(candidate) !== undefined,
      )
    ).mainTranscript;

  it('sidecar-first: every sidecar parks with noMatchingToolUse, then all resolve', async () => {
    const session = await loadReplay(await capturedMain());
    const grafter = newGrafter(session);

    // Sidecars only. No transcript has been seen, so no `tool_use` id exists.
    for (const sidecar of session.sidecars) apply(grafter, session, { kind: 'sidecar', agentId: sidecar.agentId });
    const parkedOnly = grafter.snapshot();

    // The INTERMEDIATE state is asserted, not just the final one: a grafter
    // that guessed a parent would still end up correct at the end.
    expect(parkedOnly.counts.grafted).toBe(0);
    expect(parkedOnly.counts.parked).toBe(session.sidecars.length);
    expect(parkedOnly.root.children).toEqual([]);
    expect(parkedOnly.edges).toEqual([]);
    for (const p of parkedOnly.parked) {
      expect(p.code).toBe('noMatchingToolUse');
      expect(typeof p.toolUseId).toBe('string');
      expect(p.reason.length).toBeGreaterThan(0);
    }

    // Late data: the transcripts.
    apply(grafter, session, { kind: 'main' });
    for (const agent of session.agents) {
      apply(grafter, session, { kind: 'agent', agentId: agent.batch.agentId as string });
    }
    apply(grafter, session, { kind: 'payloads' });

    expect(goldenText(grafter.snapshot())).toBe(goldenText(replay(session, inOrderScript(session))));
  });

  it('transcript-before-its-parent-tool_use-line: parks, then resolves when the line lands', async () => {
    const session = await loadReplay(await capturedMain());
    const firstToolUseLine = session.main.entries.findIndex((entry) => hasToolUse(entry));
    expect(firstToolUseLine).toBeGreaterThan(0);

    const grafter = newGrafter(session);
    // Main transcript truncated to BEFORE any `tool_use` line, plus every
    // subagent transcript and sidecar. The join keys exist; their targets
    // do not.
    apply(grafter, session, { kind: 'main', upTo: firstToolUseLine });
    for (const agent of session.agents) {
      apply(grafter, session, { kind: 'agent', agentId: agent.batch.agentId as string });
    }
    for (const sidecar of session.sidecars) {
      apply(grafter, session, { kind: 'sidecar', agentId: sidecar.agentId });
    }

    const partial = grafter.snapshot();
    expect(partial.counts.grafted).toBe(0);
    expect(partial.edges).toEqual([]);
    // Depth-1 agents park for want of the main-transcript line. Depth-2 agents
    // join fine (their parent `tool_use` is in an agent transcript we already
    // have) but their PARENT is not grafted, so they park too — and are never
    // hoisted to the root.
    const codes = parkedCodes(partial);
    expect(new Set(Object.values(codes))).toEqual(new Set(['noMatchingToolUse', 'parentNotGrafted']));
    expect(Object.values(codes)).toContain('parentNotGrafted');
    expect(childAgentIds(partial.root)).toEqual([]);

    // The rest of the main transcript arrives.
    apply(grafter, session, { kind: 'main' });
    apply(grafter, session, { kind: 'payloads' });
    expect(goldenText(grafter.snapshot())).toBe(goldenText(replay(session, inOrderScript(session))));
  });

  it('subagent-transcript-before-its-own-sidecar: parks sidecarMissing, then resolves', async () => {
    const session = await loadReplay(await capturedMain());
    const grafter = newGrafter(session);

    apply(grafter, session, { kind: 'main' });
    for (const agent of session.agents) {
      apply(grafter, session, { kind: 'agent', agentId: agent.batch.agentId as string });
    }

    const noSidecars = grafter.snapshot();
    expect(noSidecars.counts.grafted).toBe(0);
    expect(noSidecars.edges).toEqual([]);
    expect(noSidecars.parked.map((p) => p.agentId).sort()).toEqual(
      session.agents.map((a) => a.batch.agentId as string).sort(),
    );
    for (const p of noSidecars.parked) expect(p.code).toBe('sidecarMissing');
    // The main transcript's tool calls still render: one missing join does not
    // take the rest of the tree with it.
    expect(noSidecars.counts.toolNodes).toBeGreaterThan(0);

    for (const sidecar of session.sidecars) {
      apply(grafter, session, { kind: 'sidecar', agentId: sidecar.agentId });
    }
    apply(grafter, session, { kind: 'payloads' });
    expect(goldenText(grafter.snapshot())).toBe(goldenText(replay(session, inOrderScript(session))));
  });

  it('a depth-2 agent parks as parentNotGrafted while its parent is parked', async () => {
    const session = await loadReplay(await capturedMain());
    const inOrder = replay(session, inOrderScript(session));
    const deep = inOrder.edges.find((e) => e.depth >= 2);
    expect(deep, 'the capture must contain a nested spawn').toBeDefined();
    const child = deep as NonNullable<typeof deep>;
    const parentAgentId = child.parentNodeId;

    const grafter = newGrafter(session);
    apply(grafter, session, { kind: 'main' });
    for (const agent of session.agents) {
      apply(grafter, session, { kind: 'agent', agentId: agent.batch.agentId as string });
    }
    // Every sidecar EXCEPT the parent agent's.
    for (const sidecar of session.sidecars) {
      if (sidecar.agentId === parentAgentId) continue;
      apply(grafter, session, { kind: 'sidecar', agentId: sidecar.agentId });
    }

    const held = grafter.snapshot();
    const codes = parkedCodes(held);
    expect(codes[parentAgentId]).toBe('sidecarMissing');
    expect(codes[child.agentId]).toBe('parentNotGrafted');
    // Load-bearing: the orphan is NOT reattached to the root.
    expect(childAgentIds(held.root)).not.toContain(child.agentId);
    expect(graftedAgentIds(held)).not.toContain(child.agentId);

    apply(grafter, session, { kind: 'sidecar', agentId: parentAgentId });
    apply(grafter, session, { kind: 'payloads' });
    const released = grafter.snapshot();
    expect(released.parked).toEqual([]);
    expect(goldenText(released)).toBe(goldenText(inOrder));
  });

  it('four different arrival orders all converge on the same tree', async () => {
    const session = await loadReplay(await capturedMain());
    const agentIds = session.agents.map((a) => a.batch.agentId as string);
    const expected = goldenText(replay(session, inOrderScript(session)));

    const scripts: Step[][] = [
      // reverse: payloads, sidecars, agent transcripts, main
      [
        { kind: 'payloads' },
        ...session.sidecars.map((s): Step => ({ kind: 'sidecar', agentId: s.agentId })),
        ...[...agentIds].reverse().map((id): Step => ({ kind: 'agent', agentId: id })),
        { kind: 'main' },
      ],
      // interleaved: sidecar, transcript, sidecar, transcript, …
      [
        ...agentIds.flatMap((id): Step[] => [
          { kind: 'sidecar', agentId: id },
          { kind: 'agent', agentId: id },
        ]),
        { kind: 'main' },
        { kind: 'payloads' },
      ],
      // main in two halves, around everything else
      [
        { kind: 'main', upTo: Math.floor(session.main.entries.length / 2) },
        ...session.sidecars.map((s): Step => ({ kind: 'sidecar', agentId: s.agentId })),
        ...agentIds.map((id): Step => ({ kind: 'agent', agentId: id })),
        { kind: 'main' },
        { kind: 'payloads' },
      ],
      // every file replayed twice: re-reading a file must be idempotent
      [...inOrderScript(session), ...inOrderScript(session)],
    ];

    for (const [index, script] of scripts.entries()) {
      expect(goldenText(replay(session, script)), `script ${index}`).toBe(expected);
    }
  });
});

function hasToolUse(entry: TranscriptEntry): boolean {
  const message = entry['message'];
  if (typeof message !== 'object' || message === null) return false;
  const content = (message as { content?: unknown }).content;
  if (!Array.isArray(content)) return false;
  return content.some(
    (block) => typeof block === 'object' && block !== null && (block as { type?: unknown }).type === 'tool_use',
  );
}

// ---------------------------------------------------------------------------
// Refusal: a broken join never becomes a guessed parent
// ---------------------------------------------------------------------------

describe('synthetic-graft: a broken join key parks, it never guesses', () => {
  it('01 a key matching nothing stays parked and is not attached to the sole candidate', async () => {
    const result = await graftSession(graftMain('01-tool-use-id-matches-nothing'));
    if (!result.ok) throw new Error(`case 01 must fingerprint: ${result.mismatch.code}`);
    expect(result.snapshot.counts.grafted).toBe(0);
    expect(result.snapshot.edges).toEqual([]);
    expect(result.snapshot.parked).toHaveLength(1);
    expect(result.snapshot.parked[0]?.code).toBe('noMatchingToolUse');
    // The tree still renders what DID resolve: the main transcript's tools.
    expect(result.snapshot.counts.toolNodes).toBeGreaterThan(0);
    expect(childAgentIds(result.snapshot.root)).toEqual([]);
  });

  it('03 an ambiguous key parks as ambiguousJoinKey, never as the first match', async () => {
    const result = await graftSession(graftMain('03-tool-use-id-duplicated'));
    if (!result.ok) throw new Error(`case 03 must fingerprint: ${result.mismatch.code}`);
    const codes = parkedCodes(result.snapshot);
    expect(Object.values(codes)).toEqual(['ambiguousJoinKey']);
    // The unambiguous sibling still grafts — one bad key does not poison the tree.
    expect(result.snapshot.counts.grafted).toBe(1);
  });

  it('04 a sidecar naming an absent parent parks, and is NOT reattached to main', async () => {
    const result = await graftSession(graftMain('04-parent-agent-missing'));
    if (!result.ok) throw new Error(`case 04 must fingerprint: ${result.mismatch.code}`);
    const parked = result.snapshot.parked.find((p) => p.code === 'parentAgentMissing');
    expect(parked, 'the orphan must park as parentAgentMissing').toBeDefined();
    expect(graftedAgentIds(result.snapshot)).not.toContain(parked?.agentId);
    expect(childAgentIds(result.snapshot.root)).not.toContain(parked?.agentId);
  });

  it('05 a spawnDepth contradicting the chain is reported, and neither number is rewritten', async () => {
    const result = await graftSession(graftMain('05-spawn-depth-contradicts-chain'));
    if (!result.ok) throw new Error(`case 05 must fingerprint: ${result.mismatch.code}`);
    expect(result.snapshot.depthMismatches).toHaveLength(1);
    const mismatch = result.snapshot.depthMismatches[0];
    expect(mismatch?.recorded).toBe(1);
    expect(mismatch?.computed).toBe(2);
    // The agent is still grafted, at the depth the CHAIN says.
    const edge = result.snapshot.edges.find((e) => e.agentId === mismatch?.agentId);
    expect(edge?.depth).toBe(2);
    expect(edge?.recordedDepth).toBe(1);
  });

  it('06 one broken key does not stop the sound one from grafting', async () => {
    const result = await graftSession(graftMain('06-one-resolves-one-does-not'));
    if (!result.ok) throw new Error(`case 06 must fingerprint: ${result.mismatch.code}`);
    expect(result.snapshot.counts.grafted).toBe(1);
    expect(result.snapshot.counts.parked).toBe(1);
    expect(result.snapshot.parked[0]?.code).toBe('noMatchingToolUse');
  });

  it('00 the valid control grafts both agents, the second under the first', async () => {
    const result = await graftSession(graftMain('00-valid-control'));
    if (!result.ok) throw new Error(`case 00 must fingerprint: ${result.mismatch.code}`);
    expect(result.snapshot.parked).toEqual([]);
    expect(result.snapshot.counts.grafted).toBe(2);
    const depth2 = result.snapshot.edges.find((e) => e.depth === 2);
    expect(depth2).toBeDefined();
    expect(depth2?.parentNodeId).not.toBe(ROOT_NODE_ID);
  });

  it('covers every synthetic-graft case directory on disk', async () => {
    const onDisk = (await readdir(GRAFT_ROOT, { withFileTypes: true }))
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .sort();
    // Every case must at least be grafted without throwing, whatever it does.
    for (const name of onDisk) {
      const result = await graftSession(graftMain(name));
      expect(result, name).toBeDefined();
    }
    expect(onDisk.length).toBeGreaterThan(0);
  });
});

// ---------------------------------------------------------------------------
// G3: a fingerprint mismatch yields NO tree
// ---------------------------------------------------------------------------

describe('G3: a schema mismatch produces no tree at all', () => {
  const refusedCases = [
    '05-subagents-dir-renamed',
    '07-version-not-pinned',
    '08-version-changes-midfile',
    '10-meta-not-an-object',
    '12-agent-id-mismatch',
  ];

  it('every refused layout yields ok:false with no snapshot field', async () => {
    for (const name of refusedCases) {
      const result = await graftSession(layoutMain(name));
      expect(result.ok, name).toBe(false);
      if (result.ok) continue;
      expect(result.mismatch.kind).toBe('schemaMismatch');
      expect(result.mismatch.reason.length).toBeGreaterThan(0);
      // Not "a tree with zero children" — no tree key at all.
      expect('snapshot' in result).toBe(false);
    }
  });

  it('a session whose subagents directory is renamed produces no partial tree', async () => {
    // The main transcript of 05 parses perfectly and contains tool calls, so a
    // grafter that degraded instead of refusing would happily emit a root with
    // ToolNodes and no agents. It must emit nothing.
    const result = await graftSession(layoutMain('05-subagents-dir-renamed'));
    expect(result.ok).toBe(false);
  });

  it('the valid layout control still grafts', async () => {
    const result = await graftSession(layoutMain('00-valid-control'));
    if (!result.ok) throw new Error(`control must graft: ${result.mismatch.code}`);
    expect(result.snapshot.counts.grafted).toBeGreaterThan(0);
  });
});

// ---------------------------------------------------------------------------
// Whitespace-only join key
// ---------------------------------------------------------------------------

describe('a whitespace-only toolUseId is refused twice over', () => {
  it('the layout fingerprint refuses it, so no tree is built at all', async () => {
    const result = await graftSession(layoutMain('21-meta-tooluseid-whitespace'));
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.mismatch.code).toBe('metaFieldMissing');
    expect(result.mismatch.field).toBe('toolUseId');
    expect(result.mismatch.actual).toBe('blank');
    expect('snapshot' in result).toBe(false);
  });

  it('parks with missingJoinKey even though it is the only candidate', () => {
    // Fed in memory so this holds regardless of what the layout fingerprint
    // does with a blank key: the grafter refuses it independently.
    const grafter = new TreeGrafter({ sessionId: 'S', projectSlug: 'slug' });
    grafter.addTranscript({
      kind: 'main',
      path: 'S.jsonl',
      entries: [
        {
          type: 'assistant',
          timestamp: '2026-08-19T00:00:00.000Z',
          message: {
            role: 'assistant',
            content: [{ type: 'tool_use', id: 'toolu_ONLY_CANDIDATE', name: 'Agent', input: {} }],
          },
        },
      ],
    });
    grafter.addTranscript({
      kind: 'subagent',
      path: 'agent-a1.jsonl',
      agentId: 'a1',
      entries: [{ type: 'user', timestamp: '2026-08-19T00:00:01.000Z' }],
    });
    grafter.addSidecar({
      agentId: 'a1',
      metaPath: 'agent-a1.meta.json',
      meta: { agentType: 'general-purpose', description: 'blank key', toolUseId: '   ', spawnDepth: 1 },
    });

    const snapshot = grafter.snapshot();
    expect(snapshot.counts.grafted).toBe(0);
    expect(snapshot.parked.map((p) => p.code)).toEqual(['missingJoinKey']);
    // The sole candidate is still rendered as a tool node, with no agent on it.
    expect(snapshot.counts.toolNodes).toBe(1);
    expect(childAgentIds(snapshot.root)).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// Snapshot hygiene
// ---------------------------------------------------------------------------

describe('snapshots are immutable and machine-independent', () => {
  it('a snapshot is deep-frozen', async () => {
    const result = await graftSession(graftMain('00-valid-control'));
    if (!result.ok) throw new Error('must graft');
    expect(Object.isFrozen(result.snapshot)).toBe(true);
    expect(Object.isFrozen(result.snapshot.root)).toBe(true);
    expect(Object.isFrozen(result.snapshot.root.children)).toBe(true);
    walk(result.snapshot.root, (node) => expect(Object.isFrozen(node)).toBe(true));
  });

  it('two snapshots from one grafter share no node objects', async () => {
    const session = await loadReplay(graftMain('00-valid-control'));
    const grafter = newGrafter(session);
    for (const step of inOrderScript(session)) apply(grafter, session, step);
    const a = grafter.snapshot();
    const b = grafter.snapshot();
    expect(a).not.toBe(b);
    expect(a.root).not.toBe(b.root);
    expect(goldenText(a)).toBe(goldenText(b));
  });

  it('the serialized form contains no absolute path and no wall-clock value', async () => {
    for (const sessionId of await capturedSessionIds()) {
      const result = await graftSession(join(CAPTURED_SLUG, `${sessionId}.jsonl`));
      if (!result.ok) throw new Error('must graft');
      const text = goldenText(result.snapshot);
      // No drive letters, no UNC prefixes, no POSIX home paths.
      expect(/[A-Za-z]:[\\/]/.test(text)).toBe(false);
      expect(text.includes('\\\\')).toBe(false);
      expect(text.includes('/home/')).toBe(false);
      expect(text.includes('/Users/')).toBe(false);
      expect(text.toLowerCase().includes('.claude')).toBe(false);
      // The only absolute time in the file is the anchor, taken from a fixture
      // line. Everything else is an offset.
      const parsed = JSON.parse(text) as { epochAnchor: string | null };
      expect(parsed.epochAnchor).toBeTruthy();
      expect(Date.parse(parsed.epochAnchor as string)).toBeLessThan(Date.now());
      const isoCount = text.match(/\d{4}-\d{2}-\d{2}T/g) ?? [];
      expect(isoCount).toHaveLength(1);
    }
  });

  it('serializeSnapshot pins previews by digest, not verbatim', async () => {
    const session = await sessionWhere(
      'at least one `tool_use` block, so there is a preview to pin',
      (candidate) => candidate.toolUseIds.length > 0,
    );
    const result = await graftSession(session.mainTranscript);
    if (!result.ok) throw new Error(`must graft: ${result.mismatch.code}`);
    const serialized = serializeSnapshot(result.snapshot);
    const previews: unknown[] = [];
    const collect = (node: Record<string, unknown>): void => {
      if (node['node'] === 'tool') previews.push(node['inputPreview']);
      const children = node['children'];
      if (Array.isArray(children)) for (const c of children) collect(c as Record<string, unknown>);
    };
    collect(serialized.root as unknown as Record<string, unknown>);
    expect(previews.length).toBeGreaterThan(0);
    for (const p of previews) expect(String(p)).toMatch(/^sha256:[0-9a-f]{16}:\d+$/);
  });

  it('toSessionState takes liveness as an argument rather than inventing one', async () => {
    const result = await graftSession(graftMain('00-valid-control'));
    if (!result.ok) throw new Error('must graft');
    const state = toSessionState(result.snapshot, { liveness: 'idle', workspaceMatch: true });
    expect(state.liveness).toBe('idle');
    expect(state.schemaOk).toBe(true);
    expect(state.root).toBe(result.snapshot.root);
    expect(state.sessionId).toBe(result.snapshot.sessionId);
  });
});

// ---------------------------------------------------------------------------
// Degenerate input: nothing about input may crash (G3)
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// The selection layer itself
// ---------------------------------------------------------------------------

describe('fixture subjects are selected by property, not by literal id', () => {
  it('a missing property fails with a diagnostic naming it, not an ENOENT', async () => {
    // The whole point of `sessionWhere`. Asserted rather than asserted-in-a-
    // comment: a re-harvest is exactly when nobody is in a position to guess
    // why the suite went red, so the message has to do the explaining.
    const property = 'a subagent whose agentType is `a-role-that-was-never-captured`';
    let thrown: unknown;
    try {
      await sessionWhere(property, (candidate) =>
        candidate.sidecars.some((s) => s.meta?.agentType === 'a-role-that-was-never-captured'),
      );
    } catch (error: unknown) {
      thrown = error;
    }
    expect(thrown, 'an impossible property must fail').toBeInstanceOf(Error);
    const message = (thrown as Error).message;
    // Names the property that is missing...
    expect(message).toContain(property);
    // ...says it is a fixture problem rather than a code problem...
    expect(message).toContain('stale fixture reference, not a grafter bug');
    // ...and shows what the capture actually holds, so the reader can choose.
    for (const session of await capturedSessions()) expect(message).toContain(session.sessionId);
    // Explicitly NOT a filesystem error.
    expect(message).not.toContain('ENOENT');
  });

  it('every selector used by this file finds a subject in the current capture', async () => {
    const nested = await sessionWhere(
      'a nested spawn',
      (candidate) => nestedSidecarOf(candidate) !== undefined,
    );
    expect(nestedSidecarOf(nested)?.meta.spawnDepth).toBeGreaterThanOrEqual(2);

    const offloaded = await sessionWhere(
      'an offloaded payload',
      (candidate) => candidate.toolResultFiles.length > 0,
    );
    expect(offloaded.toolResultFiles.length).toBeGreaterThan(0);

    const withTools = await sessionWhere(
      'a tool_use block',
      (candidate) => candidate.toolUseIds.length > 0,
    );
    expect(withTools.toolUseIds.length).toBeGreaterThan(0);
  });

  it('the usage subject is one where the two aggregation rules actually disagree', async () => {
    // If they agreed, the token test would pass under either rule and prove
    // nothing. The selector is required to hand back a discriminating case.
    const subject = await agentWithRepeatedUsage();
    expect(subject.repeatedMessageId.length).toBeGreaterThan(0);
    expect(subject.naiveOut).toBeGreaterThan(subject.dedupedOut);
    expect(subject.dedupedOut).toBeGreaterThan(0);
  });

  it('selection is deterministic: repeated calls choose the same subject', async () => {
    const a = await agentWithRepeatedUsage();
    const b = await agentWithRepeatedUsage();
    expect(b).toEqual(a);
    const first = await sessionWhere('any session', () => true);
    const second = await sessionWhere('any session', () => true);
    expect(second.sessionId).toBe(first.sessionId);
  });
});

describe('degenerate input never throws', () => {
  it('an empty grafter yields a bare root', () => {
    const snapshot = new TreeGrafter({ sessionId: 'S', projectSlug: 'p' }).snapshot();
    expect(snapshot.root.id).toBe(ROOT_NODE_ID);
    expect(snapshot.root.children).toEqual([]);
    expect(snapshot.parked).toEqual([]);
    expect(snapshot.counts).toEqual({ grafted: 0, parked: 0, toolNodes: 0 });
    expect(snapshot.totals).toEqual({ costUsd: 0 });
    expect(snapshot.contextNow).toStrictEqual({ prompt: 0, output: 0 });
    expect(snapshot.burn).toStrictEqual({ prompt: 0, output: 0 });
  });

  it('a subagent batch with no agentId is ignored rather than guessed at', () => {
    const grafter = new TreeGrafter({ sessionId: 'S', projectSlug: 'p' });
    grafter.addTranscript({ kind: 'subagent', path: 'x.jsonl', entries: [{ type: 'user' }] });
    expect(grafter.knownAgentIds()).toEqual([]);
  });

  it('an unusable sidecar parks as sidecarUnusable', () => {
    const grafter = new TreeGrafter({ sessionId: 'S', projectSlug: 'p' });
    grafter.addSidecar({ agentId: 'a1', metaPath: 'a1.meta.json', metaFailure: 'invalid JSON' });
    const snapshot = grafter.snapshot();
    expect(snapshot.parked.map((p) => p.code)).toEqual(['sidecarUnusable']);
    expect(snapshot.parked[0]?.reason).toContain('invalid JSON');
  });

  it('entries with no message, no timestamp and no content do not throw', () => {
    const grafter = new TreeGrafter({ sessionId: 'S', projectSlug: 'p' });
    const odd: TranscriptEntry[] = [
      { type: 'file-history-snapshot' },
      { type: 'user', message: null as unknown as object },
      { type: 'assistant', message: { content: 'not an array' } },
      { type: 'assistant', message: { content: [null, 3, 'x', { type: 'tool_use' }] } },
      { type: 'assistant', timestamp: 'not-a-date', message: { content: [{ type: 'tool_result' }] } },
    ];
    grafter.addTranscript({ kind: 'main', path: 'S.jsonl', entries: odd });
    const snapshot = grafter.snapshot();
    expect(snapshot.counts.toolNodes).toBe(0);
    expect(snapshot.root.startedAt).toBe(0);
  });

  it('a tool_result with no preceding tool_use does not invent a node', () => {
    const grafter = new TreeGrafter({ sessionId: 'S', projectSlug: 'p' });
    grafter.addTranscript({
      kind: 'main',
      path: 'S.jsonl',
      entries: [
        {
          type: 'user',
          message: { content: [{ type: 'tool_result', tool_use_id: 'toolu_GHOST', content: 'x' }] },
        },
      ],
    });
    expect(grafter.snapshot().counts.toolNodes).toBe(0);
  });

  it('a sidecar with a non-string toolUseId parks with missingJoinKey', () => {
    const grafter = new TreeGrafter({ sessionId: 'S', projectSlug: 'p' });
    grafter.addSidecar({
      agentId: 'a1',
      metaPath: 'a1.meta.json',
      meta: { agentType: 't', description: 'd', spawnDepth: 1 } as unknown as SubagentMeta,
    });
    expect(grafter.snapshot().parked.map((p) => p.code)).toEqual(['missingJoinKey']);
  });
});
