/**
 * PLAN v0.5.0 Phase 3 / DoD 3.2 - the OpenCode capture procedure.
 *
 * WHAT THIS SUITE IS FOR
 * ----------------------
 * DoD 3.2's last sentence is the load-bearing one: "Replay from a clean
 * checkout with `USERPROFILE` faked fails loudly (test)." Everything else here
 * exists so that the properties the capture claims about the COMMITTED corpora
 * are checked against the corpora rather than against the README that describes
 * them.
 *
 * `USERPROFILE`, NOT `HOME`
 * -------------------------
 * `os.homedir()` reads `USERPROFILE` on Windows. A negative control that fakes
 * only `HOME` runs happily against the REAL data directory and reports a
 * confident green pass on the one check whose entire purpose is proving we
 * never touch it. That is measured, recorded history in this repository (the
 * spike's `RESOLVED 36` false pass), so this file does two things rather than
 * one: it fakes the platform's home variable and asserts the capture fails
 * loudly, AND it fakes only the OTHER variable and asserts the resolver is
 * unmoved. The second test is what proves the first one is aimed at the right
 * variable; without it the control could be faking something irrelevant and
 * nobody would know.
 *
 * A COLLECTION FAILURE LOOKS LIKE A PASS, SO SUITE 0 EXISTS
 * ---------------------------------------------------------
 * This file imports a `.mjs` script. If that import throws, vitest's summary
 * line reads "N skipped", which at a glance is not distinguishable from green -
 * exactly how a shebang on line 1 of `scripts/privacy-sweep.mjs` reached a
 * merged commit with a green report attached. The import is therefore CAUGHT,
 * not thrown, and suite 0 below depends on nothing so that it still runs and
 * still fails when that breaks. Suite 0 also reads the script's first two bytes
 * with `fs` - deliberately not through the import - because a guard against an
 * import failure must not itself import the broken module.
 *
 * NO SIZES ARE PINNED
 * -------------------
 * Standing repo law: a fixture-set count hard-coded against this capture breaks
 * on the next harvest and reads as a regression. Every assertion below is
 * emptiness, presence, or a relationship derived from the corpus itself. The
 * numbers live in each corpus's README, which is regenerated by the capture
 * that produced them.
 *
 * SCRATCH SPACE: the negative control writes into a `mkdtemp` directory under
 * `os.tmpdir()` and removes it in `afterAll`. Nothing is written inside the
 * repository, and in particular the control passes `--out` at a throwaway path
 * so that even a capture which wrongly succeeded could not touch a committed
 * fixture.
 */

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

/* ------------------------------------------------------------------ *
 * The slice of the capture script's exports this suite relies on.
 * Deliberately partial: it names only what is asserted, so a helper
 * added to the script does not have to be mirrored here.
 * ------------------------------------------------------------------ */
interface CaptureModule {
  resolveDataRoot: (env?: Record<string, string | undefined>) => string;
  normaliseRoot: (p: string) => string;
  isInsideRoot: (child: string, root: string) => boolean;
  repoIdentityRoots: (repoRoot?: string) => string[];
  isOwnLocation: (p: string, roots: string[]) => boolean;
  compareVersions: (a: string, b: string) => number;
  redactForeignPath: (p: string) => string;
  DROPPED_TABLES: readonly string[];
  REQUIRED_TABLES: readonly string[];
}

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..', '..');
const SCRIPT = path.join(REPO_ROOT, 'scripts', 'capture-opencode.mjs');
const FIXTURES = path.join(REPO_ROOT, 'fixtures');

/** The platform variable `os.homedir()` actually reads. THIS is the one to fake. */
const HOME_VAR = process.platform === 'win32' ? 'USERPROFILE' : 'HOME';
/** The one that does NOT decide the answer on this platform - the decoy. */
const DECOY_VAR = process.platform === 'win32' ? 'HOME' : 'USERPROFILE';

let mod: CaptureModule | null = null;
let loadError: unknown = null;

interface Corpus {
  dir: string;
  name: string;
  version: string;
  dbPath: string;
  db: DatabaseSync;
  tables: string[];
  columns: Map<string, string[]>;
  projects: { id: string; worktree: string }[];
  sessions: { id: string; projectId: string; directory: string; parentId: string | null; version: string }[];
  /** `projects/<token>` tallies over every captured `data` column. */
  projectsTokens: Map<string, number>;
  compaction: string[];
  taskParts: { id: string; sessionId: string; childId: string | null; parentClaim: string | null }[];
  eventSequenceCount: number;
  readme: string;
}

/**
 * THE CORPUS NAMES ARE RESOLVED AT COLLECTION TIME, ON PURPOSE.
 *
 * `it.each(...)` is evaluated while vitest is COLLECTING, before any
 * `beforeAll` has run. A list populated in `beforeAll` is still empty at that
 * moment, so every `it.each` over it generates ZERO tests - and a file that
 * generates zero tests reports as a clean pass. That is the same failure this
 * repo already shipped once (a collection failure printing "24 skipped" and
 * reading green), reached by a different route.
 *
 * So the directory listing is synchronous and at module scope; only the
 * expensive part - opening each database and scanning its bytes - happens in
 * `beforeAll`. `CORPUS_NAMES` being empty is itself asserted below.
 */
/**
 * Every `fixtures/opencode-*` directory, split into the two shapes that exist,
 * and NEITHER is discarded silently.
 *
 * Through v0.5.0 there was one shape — `fixtures/opencode-<version>/opencode.db`
 * — and the filter below was `isDirectory() && startsWith('opencode-')`. On
 * 2026-08-31 a second shape arrived: `fixtures/opencode-1.18.25/moved-project/`,
 * a WITNESS set whose database sits one level down because the directory holds
 * a case, not a release capture. The old filter picked its parent up as a
 * corpus and `beforeAll` died on `unable to open database file` — a
 * collection-time throw, which in this file is the failure mode the comment
 * above is about.
 *
 * The fix is deliberately NOT "filter to directories that happen to contain
 * `opencode.db`". That reads as tidy and is the fail-open shape rule 18 names
 * three doors into: a corpus whose database went missing would then vanish from
 * the list and the file would report a clean pass over the ones that remained.
 * Instead both shapes are CLASSIFIED, and a directory matching neither is a
 * hard failure asserted below.
 */
const OPENCODE_DIRS: string[] = fs.existsSync(FIXTURES)
  ? fs
      .readdirSync(FIXTURES, { withFileTypes: true })
      .filter((d) => d.isDirectory() && d.name.startsWith('opencode-'))
      .map((d) => d.name)
      .sort()
  : [];

/** A directory that carries its own `opencode.db`: a release capture. */
const CORPUS_NAMES: string[] = OPENCODE_DIRS.filter((name) =>
  fs.existsSync(path.join(FIXTURES, name, 'opencode.db')),
);

/**
 * A directory whose databases live in named case subdirectories: a witness set.
 * Its cases are covered by the test that owns them
 * (`src/opencode/moved.test.ts`), not by this file's capture-procedure audit.
 */
const WITNESS_DIRS: string[] = OPENCODE_DIRS.filter(
  (name) => !CORPUS_NAMES.includes(name),
);

const corpora = new Map<string, Corpus>();

/** Throws rather than returning undefined: a missing corpus must fail the test. */
function loadedCorpus(name: string): Corpus {
  const c = corpora.get(name);
  if (c === undefined) throw new Error(`corpus ${name} was not loaded in beforeAll`);
  return c;
}

/** The negative control, run ONCE. A subprocess per test is a test that passes by CPU load. */
let control: { status: number | null; stdout: string; stderr: string } | null = null;
let controlOutDir = '';
let controlHomeDir = '';
let scratch = '';

function rows<T>(db: DatabaseSync, sql: string): T[] {
  return db.prepare(sql).all() as unknown as T[];
}

function tableList(db: DatabaseSync): string[] {
  return rows<{ name: string }>(
    db,
    "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name",
  ).map((r) => String(r.name));
}

/**
 * A Claude Code project directory, anchored on `.claude` and shape-gated.
 *
 * IT USED TO BE `/projects[\\/]+([A-Za-z0-9._-]+)/`, which was correct for as
 * long as the word `projects` appeared in these corpora ONLY as
 * `.claude/projects/<slug>`. The 2026-08-28 identity scrub made the synthetic
 * home `<drive>:\Users\dev\projects\agent-deck`, so `projects\` became an
 * ordinary directory component too, and the unanchored pattern started
 * reporting ordinary paths as foreign projects.
 *
 * Worse, and familiar: a captured transcript stores a newline inside a JSON
 * string as `\` + `n`, so the prose `~/.claude/projects\ndirectory` parses as a
 * project named `ndirectory` - measured here at 56 occurrences, plus `n`,
 * `n35` and `n128`. `scripts/privacy-sweep.mjs` already hit this exact trap and
 * already fixed it the same way, with a shape gate; its comment on
 * `SLUG_SHAPE_RE` records the measurement. Two checks over the same corpora had
 * the same bug and only one of them knew.
 *
 * So: anchor on `.claude`, and require the captured token to have the SHAPE of
 * a slug. A slug is a workspace path with every separator replaced by `-`, so
 * it always begins `<drive>--` on Windows or `-` on posix. `ndirectory` does
 * not, and neither does any ordinary word.
 */
const CLAUDE_HOME_RE = /\.claude(?:[\\/]|\\{2,4})projects(?:[\\/]|\\{2,4})([A-Za-z0-9._-]+)/g;

/** `<drive>--` or a leading `-`: the shape a slug always has, and prose never. */
const SLUG_SHAPE_RE = /^(?:[A-Za-z]--|-)/;

/**
 * The root every row in a corpus must be inside, TAKEN FROM THE CORPUS.
 *
 * It used to be `repoIdentityRoots(REPO_ROOT)` - the live checkout, resolved
 * through git. That was right while the captures carried the real machine's
 * paths, and the 2026-08-28 identity scrub ended it: the corpora now declare a
 * synthetic root, so comparing them to wherever this clone happens to sit
 * asserts something that is false by construction and says nothing about G8.
 *
 * What G8 actually protects is that a capture contains ONE project and that the
 * project is this one - no other person's work rode along. Both halves survive
 * the scrub and both are checkable from the corpus alone: there must be exactly
 * one distinct root, and its last segment must be this repository's name. That
 * is also what the strays test below already claimed to do ("derived from the
 * fixture's own project.worktree, not hard-coded: this test must keep working
 * if the repository is renamed or cloned somewhere else") while its siblings
 * still resolved the live checkout.
 */
function corpusRoots(corpus: { projects: { worktree: string }[] }): string[] {
  const roots = [
    ...new Set(corpus.projects.map((p) => p.worktree.replace(/[\\/]+$/, '').toLowerCase())),
  ];
  for (const root of roots) {
    expect(
      path.basename(root),
      `a captured project root is not this repository: ${root}`,
    ).toBe(PROJECT_NAME);
  }
  return roots;
}

/**
 * This project's name, FROM THE MANIFEST.
 *
 * The first version of the check above used `path.basename(REPO_ROOT)` - the
 * name of the directory this clone happens to sit in. Measured in the
 * verification clone at `C:\v`: "expected 'agent-deck' to be 'v'", five times.
 * A guard that depends on what you called the folder you cloned into is a guard
 * that fails for everyone except its author - the same shape as the CRLF and
 * MAX_PATH traps this repository already records, and precisely the property
 * the strays test below claims for itself: "this test must keep working if the
 * repository is renamed or cloned somewhere else".
 *
 * `package.json`'s `name` is checked in, is the extension's identity, and is
 * already bound to the repository URL by `src/release/manifest.test.ts`.
 */
const PROJECT_NAME = ((): string => {
  const manifest = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'package.json'), 'utf8')) as {
    name?: unknown;
  };
  const name = String(manifest.name ?? '');
  if (name === '') throw new Error('package.json declares no name');
  return name.toLowerCase();
})();

function tallyprojects(db: DatabaseSync, into: Map<string, number>): void {
  const sources = [
    "SELECT data FROM part WHERE data GLOB '*projects*'",
    "SELECT data FROM message WHERE data GLOB '*projects*'",
    "SELECT data FROM event WHERE data GLOB '*projects*'",
  ];
  for (const sql of sources) {
    for (const row of rows<{ data: string }>(db, sql)) {
      const text = String(row.data);
      CLAUDE_HOME_RE.lastIndex = 0;
      let m = CLAUDE_HOME_RE.exec(text);
      while (m !== null) {
        const token = m[1] ?? '';
        if (SLUG_SHAPE_RE.test(token)) into.set(token, (into.get(token) ?? 0) + 1);
        m = CLAUDE_HOME_RE.exec(text);
      }
    }
  }
}

beforeAll(async () => {
  try {
    mod = (await import(/* @vite-ignore */ pathToFileURL(SCRIPT).href)) as CaptureModule;
  } catch (error: unknown) {
    loadError = error;
  }

  /* --- the committed corpora, discovered rather than named ----------- */
  for (const name of CORPUS_NAMES) {
    const dir = path.join(FIXTURES, name);
    const dbPath = path.join(dir, 'opencode.db');
    const db = new DatabaseSync(dbPath, { readOnly: true });
    const tables = tableList(db);
    const columns = new Map<string, string[]>();
    for (const t of tables) {
      columns.set(
        t,
        rows<{ name: string }>(db, `PRAGMA table_info("${t}")`).map((r) => String(r.name)),
      );
    }
    const projectsTokens = new Map<string, number>();
    tallyprojects(db, projectsTokens);

    corpora.set(name, {
      dir,
      name,
      version: name.slice('opencode-'.length),
      dbPath,
      db,
      tables,
      columns,
      projects: rows<{ id: string; worktree: string }>(db, 'SELECT id, worktree FROM project ORDER BY id').map(
        (r) => ({ id: String(r.id), worktree: String(r.worktree) }),
      ),
      sessions: rows<{
        id: string;
        project_id: string;
        directory: string;
        parent_id: string | null;
        version: string;
      }>(db, 'SELECT id, project_id, directory, parent_id, version FROM session ORDER BY id').map((r) => ({
        id: String(r.id),
        projectId: String(r.project_id),
        directory: r.directory === null ? '' : String(r.directory),
        parentId: r.parent_id === null ? null : String(r.parent_id),
        version: String(r.version),
      })),
      projectsTokens,
      compaction: rows<{ data: string }>(
        db,
        "SELECT data FROM part WHERE json_extract(data, '$.type') = 'compaction' ORDER BY id",
      ).map((r) => String(r.data)),
      taskParts: rows<{ id: string; session_id: string; child: string | null; parent_claim: string | null }>(
        db,
        `SELECT id, session_id,
                json_extract(data, '$.state.metadata.sessionId') AS child,
                json_extract(data, '$.state.metadata.parentSessionId') AS parent_claim
           FROM part WHERE json_extract(data, '$.tool') = 'task' ORDER BY id`,
      ).map((r) => ({
        id: String(r.id),
        sessionId: String(r.session_id),
        childId: r.child === null ? null : String(r.child),
        parentClaim: r.parent_claim === null ? null : String(r.parent_claim),
      })),
      eventSequenceCount: Number(
        (db.prepare('SELECT count(*) AS n FROM event_sequence').get() as { n: number }).n,
      ),
      readme: fs.readFileSync(path.join(dir, 'README.md'), 'utf8'),
    });
  }

  /* --- the negative control, run once -------------------------------- */
  scratch = fs.mkdtempSync(path.join(fs.realpathSync.native(os.tmpdir()), 'agent-deck-oc-capture-'));
  controlHomeDir = path.join(scratch, 'fake-home');
  controlOutDir = path.join(scratch, 'out');
  fs.mkdirSync(controlHomeDir, { recursive: true });

  const env: Record<string, string> = {};
  for (const [k, v] of Object.entries(process.env)) if (typeof v === 'string') env[k] = v;
  env[HOME_VAR] = controlHomeDir;

  const r = spawnSync(
    process.execPath,
    [SCRIPT, '--version', '0.0.0-negative-control', '--out', controlOutDir],
    { env, encoding: 'utf8', cwd: REPO_ROOT },
  );
  control = { status: r.status, stdout: r.stdout ?? '', stderr: r.stderr ?? '' };
}, 120_000);

afterAll(() => {
  for (const c of corpora.values()) {
    try {
      c.db.close();
    } catch {
      /* closing a read-only handle cannot lose data */
    }
  }
  if (scratch !== '') fs.rmSync(scratch, { recursive: true, force: true });
});

/* ------------------------------------------------------------------ *
 * 0. The guard that has to run even when everything else cannot
 * ------------------------------------------------------------------ */

describe('0 - the capture script is loadable at all', () => {
  it('imports without throwing', () => {
    expect(loadError, `importing ${SCRIPT} threw: ${String(loadError)}`).toBeNull();
    expect(mod).not.toBeNull();
  });

  it('has no shebang - a shebang breaks vitest COLLECTION in a CRLF checkout only', () => {
    // Read with `fs`, NOT through the import: a guard against an import failure
    // must not itself import the broken module. vite strips a hashbang with
    // /^#!.*\n/ and `.` does not match \r, so a shebang here would be invisible
    // to whoever wrote the file (LF working tree) and fatal for everyone else.
    const head = fs.readFileSync(SCRIPT).subarray(0, 2).toString('latin1');
    expect(head).not.toBe('#!');
  });

  it('exports the helpers this suite and the fingerprint work depend on', () => {
    expect(typeof mod?.resolveDataRoot).toBe('function');
    expect(typeof mod?.repoIdentityRoots).toBe('function');
    expect(typeof mod?.isOwnLocation).toBe('function');
    expect(Array.isArray(mod?.DROPPED_TABLES)).toBe(true);
    expect(Array.isArray(mod?.REQUIRED_TABLES)).toBe(true);
  });
});

/* ------------------------------------------------------------------ *
 * 1. DoD 3.2 - the negative control
 * ------------------------------------------------------------------ */

describe('1 - replay from a clean checkout with the home variable faked FAILS LOUDLY', () => {
  it('exits non-zero', () => {
    expect(control).not.toBeNull();
    expect(control?.status).not.toBe(0);
    expect(control?.status).not.toBeNull();
  });

  it('names the missing data root in its diagnostic', () => {
    const err = control?.stderr ?? '';
    expect(err).toContain('no OpenCode database at the resolved data root');
    // The faked root itself, so the message cannot be a generic failure that
    // happens to look right while pointing at the real directory.
    expect(err).toContain(path.join(controlHomeDir, '.local', 'share', 'opencode'));
  });

  it('says it did not fall back, and did not', () => {
    const err = control?.stderr ?? '';
    expect(err).toContain('Nothing was captured');
    expect(err).toContain('does not look anywhere else');
    // Nothing was produced. A silent fallback to the live database would have
    // written a database here and exited 0.
    expect(fs.existsSync(controlOutDir)).toBe(false);
  });

  it('printed no success marker', () => {
    const out = control?.stdout ?? '';
    expect(out).not.toContain('VERBATIM VERIFICATION PASSED');
    expect(out).not.toContain('captured ');
  });

  it(`faking the DECOY variable (${DECOY_VAR}) does NOT move the resolver - this is why the control fakes ${HOME_VAR}`, () => {
    // THE most important assertion in this file. `os.homedir()` reads
    // USERPROFILE on Windows, so a control that fakes only HOME measures
    // nothing and passes. This proves the control above is aimed at the
    // variable that actually decides the answer.
    const real = mod?.resolveDataRoot({ ...process.env });
    const decoyed = mod?.resolveDataRoot({ ...process.env, [DECOY_VAR]: controlHomeDir });
    expect(decoyed).toBe(real);

    const faked = mod?.resolveDataRoot({ ...process.env, [HOME_VAR]: controlHomeDir });
    expect(faked).toBe(path.join(controlHomeDir, '.local', 'share', 'opencode'));
    expect(faked).not.toBe(real);
  });

  it(`throws by name when ${HOME_VAR} is unset entirely`, () => {
    const env: Record<string, string | undefined> = { ...process.env };
    delete env[HOME_VAR];
    expect(() => mod?.resolveDataRoot(env)).toThrowError(new RegExp(HOME_VAR));
  });
});

/* ------------------------------------------------------------------ *
 * 2. G1 - the live database is opened read-only, and read-only refuses
 * ------------------------------------------------------------------ */

describe('2 - G1: read-only, always', () => {
  const raw = fs.readFileSync(SCRIPT, 'utf8');
  /**
   * CODE ONLY - comments are stripped before this suite reads the script.
   *
   * The script's own documentation quotes the read-only open in prose, and the
   * first version of the "no unreviewed open" assertion below matched that
   * quotation and failed. A test that reads a file's PROSE and reports on its
   * BEHAVIOUR is measuring the wrong thing in both directions: it can fail on a
   * correct script, and it can pass because a comment says the right words.
   */
  const source = raw
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .split('\n')
    .filter((line) => !/^\s*(\/\/|\*)/.test(line))
    .join('\n');

  it('opens the source database with { readOnly: true } and never any other way', () => {
    const opens = source.match(/new DatabaseSync\(\s*sourcePath[^)]*\)/g) ?? [];
    expect(opens.length).toBeGreaterThan(0);
    for (const open of opens) {
      expect(open).toContain('readOnly: true');
    }
  });

  it('never opens the source writable through any other spelling', () => {
    // Any `new DatabaseSync(...)` in the script must either be the read-only
    // source open or an open of the script's OWN output file. A third shape is
    // a review item, not a default.
    const all = source.match(/new DatabaseSync\([^)]*\)/g) ?? [];
    expect(all.length).toBeGreaterThan(0);
    for (const open of all) {
      const isSource = open.includes('sourcePath');
      const isOutput = open.includes('outFile');
      expect(isSource || isOutput, `unreviewed database open: ${open}`).toBe(true);
      if (isSource) expect(open).toContain('readOnly: true');
    }
  });

  it.each(CORPUS_NAMES)(
    '%s - a write through a read-only handle throws ERR_SQLITE_ERROR / errcode 8',
    (name) => {
      // The measured G1 proof: SQLITE_READONLY is primary result code 8,
      // "attempt to write a readonly database". Asserted against a COMMITTED
      // fixture, never against the live database - a test that writes to prove
      // it cannot write is not a test anyone should run twice.
      const corpus = loadedCorpus(name);
      const db = new DatabaseSync(corpus.dbPath, { readOnly: true });
      try {
        let thrown: unknown = null;
        try {
          db.exec("UPDATE session SET title = 'this must never land'");
        } catch (error: unknown) {
          thrown = error;
        }
        expect(thrown).not.toBeNull();
        const e = thrown as { code?: string; errcode?: number };
        expect(e.code).toBe('ERR_SQLITE_ERROR');
        expect(e.errcode).toBe(8);
      } finally {
        db.close();
      }
    },
  );
});

/* ------------------------------------------------------------------ *
 * 3. The committed corpora: dropped by schema, required present
 * ------------------------------------------------------------------ */

describe('3 - schema of the committed corpora', () => {
  it('there is at least one opencode corpus to check', () => {
    // Not a size assertion: zero corpora would make every test below vacuous,
    // which is the failure mode this repo has already shipped once (a suite
    // that collected nothing and reported "skipped").
    expect(CORPUS_NAMES.length).toBeGreaterThan(0);
    // And every name found at collection time really loaded, so a corpus that
    // fails to open cannot quietly drop its own tests.
    expect(corpora.size).toBe(CORPUS_NAMES.length);
  });

  it('every fixtures/opencode-* directory is CLASSIFIED, never quietly dropped', () => {
    /*
     * The partition is the assertion. `CORPUS_NAMES` is now a filter over
     * `OPENCODE_DIRS`, and a filter is exactly how a corpus disappears from a
     * suite without anybody noticing — rule 18's shape. So: the two classes
     * must account for every directory, both ways and by count (rule 19), and
     * a witness directory must really carry a database somewhere under it,
     * or it is not a witness set, it is a mistake.
     */
    expect([...CORPUS_NAMES, ...WITNESS_DIRS].sort()).toEqual([...OPENCODE_DIRS].sort());
    expect(CORPUS_NAMES.length + WITNESS_DIRS.length).toBe(OPENCODE_DIRS.length);
    for (const name of CORPUS_NAMES) {
      expect(fs.existsSync(path.join(FIXTURES, name, 'opencode.db'))).toBe(true);
    }
    for (const name of WITNESS_DIRS) {
      const dir = path.join(FIXTURES, name);
      const cases = fs
        .readdirSync(dir, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name);
      expect(cases.length, `witness set ${name} holds no case directory`).toBeGreaterThan(0);
      for (const c of cases) {
        expect(
          fs.existsSync(path.join(dir, c, 'opencode.db')),
          `${name}/${c} carries no opencode.db`,
        ).toBe(true);
      }
    }
  });

  it.each(CORPUS_NAMES)('%s - none of the secret-bearing tables exist', (name) => {
    const corpus = loadedCorpus(name);
    const dropped = mod?.DROPPED_TABLES ?? [];
    expect(dropped.length).toBeGreaterThan(0);
    for (const t of dropped) {
      expect(corpus.tables, `${name} still has the dropped table ${t}`).not.toContain(t);
    }
  });

  it.each(CORPUS_NAMES)('%s - all six required tables exist', (name) => {
    const corpus = loadedCorpus(name);
    for (const t of mod?.REQUIRED_TABLES ?? []) {
      expect(corpus.tables, `${name} is missing the required table ${t}`).toContain(t);
    }
  });

  it.each(CORPUS_NAMES)(
    '%s - no credential-shaped COLUMN exists anywhere, which is what "dropped by schema" buys',
    (name) => {
      // Row counts are a coincidence of the capture moment; the schema is the
      // risk. If no column can hold a token, a future OpenCode release that
      // starts populating one cannot leak through an existing fixture.
      const corpus = loadedCorpus(name);
      const forbidden = ['access_token', 'refresh_token', 'secret'];
      for (const [table, cols] of corpus.columns) {
        for (const col of cols) {
          expect(forbidden, `${name}.${table}.${col}`).not.toContain(col);
        }
      }
    },
  );
});

/* ------------------------------------------------------------------ *
 * 4. G8 over the committed corpora
 * ------------------------------------------------------------------ */

describe('4 - G8: every captured row belongs to this repository', () => {
  it.each(CORPUS_NAMES)(
    '%s - every project.worktree resolves to this repo, case-insensitively',
    (name) => {
      const corpus = loadedCorpus(name);
      const roots = corpusRoots(corpus);
      expect(roots.length, `${name} declares no project root at all`).toBe(1);
      expect(corpus.projects.length).toBeGreaterThan(0);
      for (const p of corpus.projects) {
        expect(
          mod?.isOwnLocation(p.worktree, roots),
          `${name}: project ${p.id} worktree ${p.worktree} is not the corpus root (${roots.join(', ')})`,
        ).toBe(true);
      }
    },
    // Rule 14. `repoIdentityRoots` resolves real paths, and the FIRST call in
    // a worker pays for every one after it: this case measures 67 ms for the
    // second corpus and timed out at the 5 s default for the first, under
    // whole-suite load. Same class as the six hooks Phase 5.5's suite-integrity
    // commit budgeted, arriving on an `it` instead of a `beforeAll`.
    120_000,
  );

  it('the drive-letter case trap is actually handled, not merely claimed', () => {
    // `c--Users-...` and `C--Users-...` both occur on Windows for the same
    // directory. A case-sensitive comparison here would reject a correct
    // capture on one boot and accept it on the next.
    const corpus = loadedCorpus(CORPUS_NAMES[0] ?? '');
    const roots = corpusRoots(corpus);
    const first = corpus.projects[0]?.worktree ?? '';
    expect(first).not.toBe('');
    expect(mod?.isOwnLocation(first.toUpperCase(), roots)).toBe(true);
    expect(mod?.isOwnLocation(first.toLowerCase(), roots)).toBe(true);
  });

  it.each(CORPUS_NAMES)('%s - every session belongs to a captured project', (name) => {
    const corpus = loadedCorpus(name);
    const ids = corpus.projects.map((p) => p.id);
    expect(corpus.sessions.length).toBeGreaterThan(0);
    for (const s of corpus.sessions) {
      expect(ids, `${name}: session ${s.id} belongs to project ${s.projectId}`).toContain(s.projectId);
    }
  });

  it.each(CORPUS_NAMES)('%s - every session directory is inside this repository', (name) => {
    const corpus = loadedCorpus(name);
    const roots = corpusRoots(corpus);
    for (const s of corpus.sessions) {
      if (s.directory === '') continue;
      expect(mod?.isOwnLocation(s.directory, roots), `${name}: session ${s.id} -> ${s.directory}`).toBe(true);
    }
  });

  it.each(CORPUS_NAMES)(
    '%s - the only project named in the captured bytes is this one',
    (name) => {
      // The own token is derived from the fixture's own `project.worktree`, not
      // hard-coded: this test must keep working if the repository is renamed or
      // cloned somewhere else.
      const corpus = loadedCorpus(name);
      const own = new Set(
        corpus.projects.map((p) => path.basename(p.worktree.replace(/[\\/]+$/, '')).toLowerCase()),
      );
      const strays: string[] = [];
      for (const [token, count] of corpus.projectsTokens) {
        // `agent-deck.vsix` and friends: a token that STARTS with an own name
        // is a filename in this project, not another project.
        //
        // ...and a token that ENDS with one is this project's own SLUG, which
        // is the workspace path with every separator replaced by `-`. Before
        // the 2026-08-28 scrub the slug happened not to reach this tally at
        // all; the synthetic root put `.claude/projects/<slug>` into the
        // captured text, so the slug now shows up and is as own as it gets.
        const t = token.toLowerCase();
        if ([...own].some((o) => t === o || t.startsWith(o) || t.endsWith(`-${o}`))) continue;
        strays.push(`${token} x${count}`);
      }
      expect(strays, `${name} names other projects: ${strays.join(', ')}`).toEqual([]);
    },
  );

  it('the G8 log redacts a foreign location instead of publishing it', () => {
    // The G8 record must not itself be a G8 violation. `redactForeignPath`
    // keeps the root and the segment count and drops every name.
    const redacted = mod?.redactForeignPath('D:/Users/someone/src/some-other-project') ?? '';
    expect(redacted).toContain('redacted');
    expect(redacted).not.toContain('someone');
    expect(redacted).not.toContain('some-other-project');
    expect(mod?.redactForeignPath('/')).toBe('/');
  });

  it.each(CORPUS_NAMES)('%s - the README does not publish a foreign location', (name) => {
    const corpus = loadedCorpus(name);
    const own = corpus.projects.map((p) =>
      path.basename(p.worktree.replace(/[\\/]+$/, '')).toLowerCase(),
    );
    CLAUDE_HOME_RE.lastIndex = 0;
    let m = CLAUDE_HOME_RE.exec(corpus.readme);
    const strays: string[] = [];
    while (m !== null) {
      const token = m[1] ?? '';
      const t = token.toLowerCase();
      if (!own.some((o) => t === o || t.startsWith(o))) strays.push(token);
      m = CLAUDE_HOME_RE.exec(corpus.readme);
    }
    expect(strays, `${name}/README.md names other projects: ${strays.join(', ')}`).toEqual([]);
  });
});

/* ------------------------------------------------------------------ *
 * 5. DoD 3.3 - the shapes the harvest exists to pin
 * ------------------------------------------------------------------ */

describe('5 - the harvest set carries the shapes, not a row count', () => {
  it.each(CORPUS_NAMES)('%s - README names its own version and role', (name) => {
    const corpus = loadedCorpus(name);
    expect(corpus.readme).toContain(corpus.version);
    expect(corpus.readme).toMatch(/\*\*(anchor|witness)\*\*/);
    expect(corpus.readme).toContain('DoD 3.3 checklist');
  });

  it.each(CORPUS_NAMES)(
    '%s - every session in the corpus carries the version the directory names',
    (name) => {
      const corpus = loadedCorpus(name);
      for (const s of corpus.sessions) {
        expect(s.version, `${name}: session ${s.id} is version ${s.version}`).toBe(corpus.version);
      }
    },
  );

  it.each(CORPUS_NAMES)(
    '%s - there is one event-cursor snapshot per captured session',
    (name) => {
      // Derived from the corpus, not pinned: the relationship is the property,
      // the number is an accident of the harvest.
      const corpus = loadedCorpus(name);
      expect(corpus.eventSequenceCount).toBe(corpus.sessions.length);
    },
  );

  it.each(CORPUS_NAMES)(
    '%s - the subagent join is a primary key in both directions where it resolves',
    (name) => {
      const corpus = loadedCorpus(name);
      const byId = new Map(corpus.sessions.map((s) => [s.id, s]));
      let resolved = 0;
      for (const t of corpus.taskParts) {
        if (t.childId === null) continue; // the parked case, asserted separately
        const child = byId.get(t.childId);
        if (child === undefined) continue; // child outside this version's corpus
        expect(child.parentId, `${name}: ${t.id} child ${t.childId} parent disagreement`).toBe(t.sessionId);
        expect(t.parentClaim, `${name}: ${t.id} parentSessionId disagreement`).toBe(t.sessionId);
        resolved += 1;
      }
      expect(resolved).toBeGreaterThan(0);
    },
  );

  it('the ANCHOR corpus ticks every DoD 3.3 checklist row', () => {
    // The anchor is the newest version present, derived rather than named, so
    // this keeps working when the next harvest moves the anchor. DoD 3.3 is a
    // requirement on ONE corpus ("in one fixtures/opencode-<version>/"), which
    // is why a witness may legitimately carry a "covered by the anchor" marker
    // and the anchor may not.
    const names = [...corpora.keys()];
    expect(names.length).toBeGreaterThan(0);
    const anchorName = names.reduce((best, n) =>
      (mod?.compareVersions(loadedCorpus(n).version, loadedCorpus(best).version) ?? 0) > 0 ? n : best,
    );
    const anchor = loadedCorpus(anchorName);
    // Only the checklist TABLE rows: the prose above it explains what a cross
    // would mean and legitimately contains one.
    const checklistRows = anchor.readme
      .split('\n')
      .filter((line) => /^\|\s*\d+\s*\|/.test(line));
    expect(checklistRows.length).toBeGreaterThan(0);
    const unticked = checklistRows.filter((line) => line.includes('❌'));
    expect(unticked, `${anchorName} has unticked DoD 3.3 rows:\n${unticked.join('\n')}`).toEqual([]);
    expect(anchor.readme).toContain('**anchor**');
  });

  it('a `task` part with NO sessionId is present in the fixture set - the parked case', () => {
    const parked = [...corpora.values()].flatMap((c) => c.taskParts.filter((t) => t.childId === null));
    expect(parked.length).toBeGreaterThan(0);
  });

  it('the fixture set proves `tail_start_id` is OPTIONAL on a compaction part', () => {
    // This is the entire reason there is an anchor AND a witness. It is a
    // relationship across the set, not a count: one corpus carries the field
    // and another does not, so a fingerprint cannot mistake it for a
    // requirement and a parser cannot forget to look for it.
    const all = [...corpora.values()].flatMap((c) =>
      c.compaction.map((d) => JSON.parse(d) as Record<string, unknown>),
    );
    expect(all.length).toBeGreaterThan(0);
    const withTail = all.filter((c) => 'tail_start_id' in c);
    const withoutTail = all.filter((c) => !('tail_start_id' in c));
    expect(withTail.length, 'no compaction row carries tail_start_id').toBeGreaterThan(0);
    expect(withoutTail.length, 'no compaction row omits tail_start_id').toBeGreaterThan(0);
    for (const c of all) expect(c.type).toBe('compaction');
  });

  it.each(CORPUS_NAMES)(
    '%s - reasoning text is present VERBATIM, which is what makes the G4 test real',
    (name) => {
      // The inverse of the CC trap: CC's thinking blocks are empty on disk and
      // the bytes live in `signature`, so a G4 test asserting only on thinking
      // text is vacuous. Here the bytes are plainly in `text` - so a truncated
      // or normalised fixture would silently make Phase 4's G4 test vacuous in
      // the same way. This asserts the fixture still has something to redact.
      const corpus = loadedCorpus(name);
      const r = corpus.db
        .prepare(
          `SELECT count(*) AS n, max(length(json_extract(data, '$.text'))) AS m
             FROM part WHERE json_extract(data, '$.type') = 'reasoning'`,
        )
        .get() as { n: number; m: number | null };
      expect(Number(r.n)).toBeGreaterThan(0);
      expect(Number(r.m ?? 0)).toBeGreaterThan(1000);
    },
  );

  it.each(CORPUS_NAMES)(
    '%s - an inline tool output survived at full length (no truncation was applied)',
    (name) => {
      const corpus = loadedCorpus(name);
      const r = corpus.db
        .prepare(
          `SELECT max(length(json_extract(data, '$.state.output'))) AS m
             FROM part WHERE json_extract(data, '$.type') = 'tool'`,
        )
        .get() as { m: number | null };
      expect(Number(r.m ?? 0)).toBeGreaterThanOrEqual(50_000);
    },
  );

  it.each(CORPUS_NAMES)(
    '%s - completed AND error tool parts are both present',
    (name) => {
      const corpus = loadedCorpus(name);
      const states = Array.from(
        rows<{ s: string | null }>(
          corpus.db,
          `SELECT DISTINCT json_extract(data, '$.state.status') AS s
             FROM part WHERE json_extract(data, '$.type') = 'tool'`,
        ).map((r) => (r.s === null ? '' : String(r.s))),
      );
      expect(states).toContain('completed');
      expect(states).toContain('error');
    },
  );

  it.each(CORPUS_NAMES)('%s - step-finish rows carry non-zero tokens', (name) => {
    const corpus = loadedCorpus(name);
    const r = corpus.db
      .prepare(
        `SELECT count(*) AS n FROM part
          WHERE json_extract(data, '$.type') = 'step-finish'
            AND json_extract(data, '$.tokens.total') > 0`,
      )
      .get() as { n: number };
    expect(Number(r.n)).toBeGreaterThan(0);
  });

  it.each(CORPUS_NAMES)(
    '%s - the out-of-scope tables were KEPT, so "unknown tables are ignored" has a real fixture',
    (name) => {
      // Contract §3: unknown tables are ignored, not refused. A fixture holding
      // only the six required tables would pass a fingerprint that refuses
      // every real OpenCode database on the planet.
      const corpus = loadedCorpus(name);
      const required = new Set(mod?.REQUIRED_TABLES ?? []);
      const extra = corpus.tables.filter((t) => !required.has(t));
      expect(extra.length).toBeGreaterThan(0);
    },
  );
});
